-- Leaderboard completeness: score operators, per-score metadata, client
-- submissions, periods, and attempt caps.
--
-- The entry model changes from an append-only submission log (best derived
-- with MIN/MAX at read time) to ONE row per (leaderboard, player, period).
-- The operator (best/set/incr) is applied at write time by an upsert, which
-- keeps every read query a plain ORDER BY score and makes the attempt counter
-- and the period boundary natural columns. The collapse below keeps each
-- player's best row per the board's sort order, so nothing a client could
-- read through the API changes.
--
-- row_security = off: the collapse must see every tenant's entries. The
-- migration role either may bypass RLS (and the collapse is exact) or the
-- migration fails loudly — it can never silently keep duplicates.
SET LOCAL row_security = off;

-- Board-level feature columns. current_period starts at 0 and only ever
-- increments; entries carry the period they were submitted in, so past
-- periods stay readable in place after a reset.
ALTER TABLE leaderboards
ADD COLUMN score_operator text NOT NULL DEFAULT 'best',
ADD COLUMN metadata jsonb,
ADD COLUMN client_submissions boolean NOT NULL DEFAULT false,
ADD COLUMN score_min bigint,
ADD COLUMN score_max bigint,
ADD COLUMN reset_schedule text NOT NULL DEFAULT 'none',
ADD COLUMN attempt_cap integer,
ADD COLUMN current_period integer NOT NULL DEFAULT 0,
ADD COLUMN period_started_at timestamptz,
ADD COLUMN next_reset_at timestamptz,
ADD CONSTRAINT leaderboards_score_operator_check
    CHECK (score_operator IN ('best', 'set', 'incr')),
ADD CONSTRAINT leaderboards_reset_schedule_check
    CHECK (reset_schedule IN ('none', 'daily', 'weekly', 'monthly')),
ADD CONSTRAINT leaderboards_attempt_cap_check
    CHECK (attempt_cap IS NULL OR attempt_cap > 0),
ADD CONSTRAINT leaderboards_score_bounds_check
    CHECK (score_min IS NULL OR score_max IS NULL OR score_min <= score_max);

ALTER TABLE leaderboard_entries
ADD COLUMN period integer NOT NULL DEFAULT 0,
ADD COLUMN attempts integer NOT NULL DEFAULT 1,
ADD COLUMN metadata jsonb,
ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now();

-- Collapse the submission log: keep each player's best-ranked entry per the
-- board's sort order (ties break on the earliest row), count the rest as
-- attempts, and remember the first submission time.
WITH ranked AS (
    SELECT le.id,
           ROW_NUMBER() OVER (
               PARTITION BY le.leaderboard_id, le.player_id
               ORDER BY
                 CASE WHEN l.sort_order = 'asc' THEN le.score END ASC,
                 CASE WHEN l.sort_order <> 'asc' THEN le.score END DESC,
                 le.id ASC
           ) AS rn,
           COUNT(*) OVER (PARTITION BY le.leaderboard_id, le.player_id) AS n,
           MIN(le.recorded_at) OVER (PARTITION BY le.leaderboard_id, le.player_id) AS first_at,
           MAX(le.recorded_at) OVER (PARTITION BY le.leaderboard_id, le.player_id) AS last_at
    FROM leaderboard_entries le
    JOIN leaderboards l ON l.id = le.leaderboard_id
)
UPDATE leaderboard_entries le
SET attempts = r.n,
    recorded_at = r.first_at,
    updated_at = r.last_at
FROM ranked r
WHERE le.id = r.id AND r.rn = 1;

DELETE FROM leaderboard_entries le
USING (
    SELECT le.id,
           ROW_NUMBER() OVER (
               PARTITION BY le.leaderboard_id, le.player_id
               ORDER BY
                 CASE WHEN l.sort_order = 'asc' THEN le.score END ASC,
                 CASE WHEN l.sort_order <> 'asc' THEN le.score END DESC,
                 le.id ASC
           ) AS rn
    FROM leaderboard_entries le
    JOIN leaderboards l ON l.id = le.leaderboard_id
) r
WHERE le.id = r.id AND r.rn > 1;

-- The upsert's arbiter. leaderboard_id implies the tenant, so tenant_id is
-- not part of the key.
CREATE UNIQUE INDEX leaderboard_entries_player_period_uniq
    ON leaderboard_entries (leaderboard_id, player_id, period);

-- One-row-per-player reads sort directly on score; the old aggregate-shaped
-- indexes no longer match any query.
DROP INDEX leaderboard_entries_best_score_asc_idx;
DROP INDEX leaderboard_entries_best_score_idx;
DROP INDEX leaderboard_entries_top_idx;
DROP INDEX leaderboard_entries_player_idx;
CREATE INDEX leaderboard_entries_period_score_idx
    ON leaderboard_entries (tenant_id, leaderboard_id, period, score);

-- Archive row per finished period; entries stay in leaderboard_entries under
-- their period number. The current period lives on the board itself.
CREATE TABLE leaderboard_periods (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    leaderboard_id bigint NOT NULL REFERENCES leaderboards(id) ON DELETE CASCADE,
    period integer NOT NULL,
    started_at timestamptz NOT NULL,
    ended_at timestamptz NOT NULL,
    UNIQUE (leaderboard_id, period)
);

CREATE INDEX leaderboard_periods_tenant_id_idx ON leaderboard_periods (tenant_id);

ALTER TABLE leaderboard_periods ENABLE ROW LEVEL SECURITY;
ALTER TABLE leaderboard_periods FORCE ROW LEVEL SECURITY;
CREATE POLICY leaderboard_periods_isolation ON leaderboard_periods
    USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::bigint);

GRANT SELECT, INSERT, DELETE, UPDATE ON leaderboard_periods TO ggscale_app;
GRANT SELECT, USAGE ON SEQUENCE leaderboard_periods_id_seq TO ggscale_app;
