// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: allowed_origins.sql

package sqlcgen

import (
	"context"
)

const getAllowedOrigins = `-- name: GetAllowedOrigins :one
SELECT allowed_origins
FROM projects
WHERE id = $1
  AND tenant_id = current_setting('app.tenant_id', true)::bigint
  AND deleted_at IS NULL
`

func (q *Queries) GetAllowedOrigins(ctx context.Context, projectID int64) ([]string, error) {
	row := q.db.QueryRow(ctx, getAllowedOrigins, projectID)
	var allowed_origins []string
	err := row.Scan(&allowed_origins)
	return allowed_origins, err
}

const getAllowedOriginsForUpdate = `-- name: GetAllowedOriginsForUpdate :one
SELECT allowed_origins
FROM projects
WHERE id = $1
  AND tenant_id = current_setting('app.tenant_id', true)::bigint
  AND deleted_at IS NULL
FOR UPDATE
`

func (q *Queries) GetAllowedOriginsForUpdate(ctx context.Context, projectID int64) ([]string, error) {
	row := q.db.QueryRow(ctx, getAllowedOriginsForUpdate, projectID)
	var allowed_origins []string
	err := row.Scan(&allowed_origins)
	return allowed_origins, err
}

const listAllProjectAllowedOrigins = `-- name: ListAllProjectAllowedOrigins :many
SELECT origin::text FROM all_project_allowed_origins() AS origin
`

// Runs with no tenant set; see all_project_allowed_origins().
func (q *Queries) ListAllProjectAllowedOrigins(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listAllProjectAllowedOrigins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var origin string
		if err := rows.Scan(&origin); err != nil {
			return nil, err
		}
		items = append(items, origin)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAllowedOrigins = `-- name: SetAllowedOrigins :exec
UPDATE projects
SET allowed_origins = $1::text[]
WHERE id = $2
  AND tenant_id = current_setting('app.tenant_id', true)::bigint
  AND deleted_at IS NULL
`

type SetAllowedOriginsParams struct {
	Origins   []string
	ProjectID int64
}

func (q *Queries) SetAllowedOrigins(ctx context.Context, arg SetAllowedOriginsParams) error {
	_, err := q.db.Exec(ctx, setAllowedOrigins, arg.Origins, arg.ProjectID)
	return err
}
