// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (tenant_id, project_id, key_hash, label, scopes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at
`

type CreateAPIKeyParams struct {
	TenantID  int64
	ProjectID *int64
	KeyHash   []byte
	Label     *string
	Scopes    []string
}

type CreateAPIKeyRow struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.TenantID,
		arg.ProjectID,
		arg.KeyHash,
		arg.Label,
		arg.Scopes,
	)
	var i CreateAPIKeyRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createDashboardAPIKey = `-- name: CreateDashboardAPIKey :one
WITH args AS (
    SELECT
        $1::bigint AS project_id,
        $2::bytea AS key_hash,
        $3::text AS label
), tenant_ctx AS (
    SELECT nullif(current_setting('app.tenant_id', true), '')::bigint AS tenant_id
),
project_ctx AS (
    SELECT args.project_id
    FROM args
    WHERE args.project_id IS NULL
    UNION ALL
    SELECT p.id AS project_id
    FROM projects p, tenant_ctx t, args
    WHERE p.id = args.project_id AND p.tenant_id = t.tenant_id
)
INSERT INTO api_keys (tenant_id, project_id, key_hash, label, scopes)
SELECT t.tenant_id, p.project_id, args.key_hash, nullif(trim(args.label), ''), '{}'::text[]
FROM tenant_ctx t
CROSS JOIN project_ctx p
CROSS JOIN args
RETURNING id, created_at
`

type CreateDashboardAPIKeyParams struct {
	ProjectID *int64
	KeyHash   []byte
	Label     string
}

type CreateDashboardAPIKeyRow struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateDashboardAPIKey(ctx context.Context, arg CreateDashboardAPIKeyParams) (CreateDashboardAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, createDashboardAPIKey, arg.ProjectID, arg.KeyHash, arg.Label)
	var i CreateDashboardAPIKeyRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT k.id, k.tenant_id, k.project_id, k.revoked_at, t.tier
FROM api_keys k
JOIN tenants t ON t.id = k.tenant_id
WHERE k.key_hash = $1
`

type GetAPIKeyByHashRow struct {
	ID        int64
	TenantID  int64
	ProjectID *int64
	RevokedAt pgtype.Timestamptz
	Tier      string
}

// Bootstrap query used by the tenant middleware to resolve a Bearer token
// to its tenant_id + project_id + tenant tier. Runs without an
// app.tenant_id GUC set; the api_keys_bootstrap policy in 0010 lets it
// through. Note: this query does NOT filter by tenants table RLS because
// tenants.id = current_setting GUC is unset at bootstrap; if/when we add
// a bootstrap policy on tenants, the JOIN keeps working.
func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash []byte) (GetAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i GetAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.RevokedAt,
		&i.Tier,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, project_id, label, scopes, created_at, revoked_at
FROM api_keys
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
ORDER BY id DESC
`

type ListAPIKeysRow struct {
	ID        int64
	ProjectID *int64
	Label     *string
	Scopes    []string
	CreatedAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) ListAPIKeys(ctx context.Context) ([]ListAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPIKeysRow
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Label,
			&i.Scopes,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys
SET revoked_at = now()
WHERE id = $1 AND tenant_id = current_setting('app.tenant_id', true)::bigint
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, id)
	return err
}

const updateAPIKeyLabel = `-- name: UpdateAPIKeyLabel :exec
UPDATE api_keys
SET label = nullif(trim($1::text), '')
WHERE id = $2 AND tenant_id = current_setting('app.tenant_id', true)::bigint
`

type UpdateAPIKeyLabelParams struct {
	Label string
	ID    int64
}

func (q *Queries) UpdateAPIKeyLabel(ctx context.Context, arg UpdateAPIKeyLabelParams) error {
	_, err := q.db.Exec(ctx, updateAPIKeyLabel, arg.Label, arg.ID)
	return err
}
