// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlcgen

import (
	"context"
)

const writeAudit = `-- name: WriteAudit :exec
INSERT INTO audit_log (tenant_id, actor_user_id, action, target, payload)
VALUES (
    current_setting('app.tenant_id', true)::bigint,
    $1, $2, $3, $4
)
`

type WriteAuditParams struct {
	ActorUserID *int64
	Action      string
	Target      *string
	Payload     []byte
}

func (q *Queries) WriteAudit(ctx context.Context, arg WriteAuditParams) error {
	_, err := q.db.Exec(ctx, writeAudit,
		arg.ActorUserID,
		arg.Action,
		arg.Target,
		arg.Payload,
	)
	return err
}

const writePlatformAudit = `-- name: WritePlatformAudit :exec
INSERT INTO platform_audit_log (actor_user_id, action, target, payload)
VALUES ($1, $2, $3, $4)
`

type WritePlatformAuditParams struct {
	ActorUserID *int64
	Action      string
	Target      *string
	Payload     []byte
}

func (q *Queries) WritePlatformAudit(ctx context.Context, arg WritePlatformAuditParams) error {
	_, err := q.db.Exec(ctx, writePlatformAudit,
		arg.ActorUserID,
		arg.Action,
		arg.Target,
		arg.Payload,
	)
	return err
}
