// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAnonymousEndUser = `-- name: CreateAnonymousEndUser :one
INSERT INTO end_users (tenant_id, project_id, external_id)
VALUES (
    current_setting('app.tenant_id', true)::bigint,
    $1,
    $2
)
RETURNING id, external_id, created_at
`

type CreateAnonymousEndUserParams struct {
	ProjectID  int64
	ExternalID string
}

type CreateAnonymousEndUserRow struct {
	ID         int64
	ExternalID string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateAnonymousEndUser(ctx context.Context, arg CreateAnonymousEndUserParams) (CreateAnonymousEndUserRow, error) {
	row := q.db.QueryRow(ctx, createAnonymousEndUser, arg.ProjectID, arg.ExternalID)
	var i CreateAnonymousEndUserRow
	err := row.Scan(&i.ID, &i.ExternalID, &i.CreatedAt)
	return i, err
}

const createEmailEndUser = `-- name: CreateEmailEndUser :one
INSERT INTO end_users (
    tenant_id, project_id, external_id, email, password_hash,
    email_verification_hash, email_verification_expires_at
)
VALUES (
    current_setting('app.tenant_id', true)::bigint,
    $1, $2, $3, $4, $5, $6
)
RETURNING id
`

type CreateEmailEndUserParams struct {
	ProjectID                  int64
	ExternalID                 string
	Email                      *string
	PasswordHash               []byte
	EmailVerificationHash      []byte
	EmailVerificationExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateEmailEndUser(ctx context.Context, arg CreateEmailEndUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, createEmailEndUser,
		arg.ProjectID,
		arg.ExternalID,
		arg.Email,
		arg.PasswordHash,
		arg.EmailVerificationHash,
		arg.EmailVerificationExpiresAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (tenant_id, end_user_id, refresh_hash, expires_at)
VALUES (
    current_setting('app.tenant_id', true)::bigint,
    $1, $2, $3
)
RETURNING id, created_at
`

type CreateSessionParams struct {
	EndUserID   int64
	RefreshHash []byte
	ExpiresAt   pgtype.Timestamptz
}

type CreateSessionRow struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession, arg.EndUserID, arg.RefreshHash, arg.ExpiresAt)
	var i CreateSessionRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getEndUserByEmail = `-- name: GetEndUserByEmail :one
SELECT id, project_id, password_hash, email_verified_at
FROM end_users
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND project_id = $1
  AND email = $2
  AND deleted_at IS NULL
`

type GetEndUserByEmailParams struct {
	ProjectID int64
	Email     *string
}

type GetEndUserByEmailRow struct {
	ID              int64
	ProjectID       int64
	PasswordHash    []byte
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) GetEndUserByEmail(ctx context.Context, arg GetEndUserByEmailParams) (GetEndUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getEndUserByEmail, arg.ProjectID, arg.Email)
	var i GetEndUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const getEndUserByExternalID = `-- name: GetEndUserByExternalID :one
SELECT id, project_id, email_verified_at
FROM end_users
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND project_id = $1
  AND external_id = $2
  AND deleted_at IS NULL
`

type GetEndUserByExternalIDParams struct {
	ProjectID  int64
	ExternalID string
}

type GetEndUserByExternalIDRow struct {
	ID              int64
	ProjectID       int64
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) GetEndUserByExternalID(ctx context.Context, arg GetEndUserByExternalIDParams) (GetEndUserByExternalIDRow, error) {
	row := q.db.QueryRow(ctx, getEndUserByExternalID, arg.ProjectID, arg.ExternalID)
	var i GetEndUserByExternalIDRow
	err := row.Scan(&i.ID, &i.ProjectID, &i.EmailVerifiedAt)
	return i, err
}

const getSessionByRefreshHash = `-- name: GetSessionByRefreshHash :one
SELECT id, end_user_id, expires_at, revoked_at
FROM sessions
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND refresh_hash = $1
`

type GetSessionByRefreshHashRow struct {
	ID        int64
	EndUserID int64
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) GetSessionByRefreshHash(ctx context.Context, refreshHash []byte) (GetSessionByRefreshHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshHash, refreshHash)
	var i GetSessionByRefreshHashRow
	err := row.Scan(
		&i.ID,
		&i.EndUserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getTenantCustomTokenSecret = `-- name: GetTenantCustomTokenSecret :one
SELECT custom_token_secret
FROM tenants
WHERE id = current_setting('app.tenant_id', true)::bigint
`

func (q *Queries) GetTenantCustomTokenSecret(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, getTenantCustomTokenSecret)
	var custom_token_secret []byte
	err := row.Scan(&custom_token_secret)
	return custom_token_secret, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = now()
WHERE id = $1
  AND tenant_id = current_setting('app.tenant_id', true)::bigint
  AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const revokeSessionByRefreshHash = `-- name: RevokeSessionByRefreshHash :exec
UPDATE sessions
SET revoked_at = now()
WHERE refresh_hash = $1
  AND tenant_id = current_setting('app.tenant_id', true)::bigint
  AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionByRefreshHash(ctx context.Context, refreshHash []byte) error {
	_, err := q.db.Exec(ctx, revokeSessionByRefreshHash, refreshHash)
	return err
}

const upsertEndUserByExternalID = `-- name: UpsertEndUserByExternalID :one
INSERT INTO end_users (tenant_id, project_id, external_id)
VALUES (
    current_setting('app.tenant_id', true)::bigint,
    $1, $2
)
ON CONFLICT (tenant_id, project_id, external_id)
    WHERE deleted_at IS NULL
DO UPDATE SET external_id = EXCLUDED.external_id
RETURNING id
`

type UpsertEndUserByExternalIDParams struct {
	ProjectID  int64
	ExternalID string
}

// Custom-token flow: find existing end_user with this external_id under
// (tenant, project) or create one. Idempotent across repeated calls.
func (q *Queries) UpsertEndUserByExternalID(ctx context.Context, arg UpsertEndUserByExternalIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertEndUserByExternalID, arg.ProjectID, arg.ExternalID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const verifyEmailByTokenHash = `-- name: VerifyEmailByTokenHash :one
UPDATE end_users
SET email_verified_at              = now(),
    email_verification_hash        = NULL,
    email_verification_expires_at  = NULL
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND email_verification_hash = $1
  AND email_verification_expires_at > now()
RETURNING id
`

func (q *Queries) VerifyEmailByTokenHash(ctx context.Context, emailVerificationHash []byte) (int64, error) {
	row := q.db.QueryRow(ctx, verifyEmailByTokenHash, emailVerificationHash)
	var id int64
	err := row.Scan(&id)
	return id, err
}
