// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearPlayerVerificationCode = `-- name: ClearPlayerVerificationCode :exec
UPDATE project_players
SET email_verification_code_hash    = NULL,
    email_verification_salt         = NULL,
    email_verification_expires_at   = NULL,
    email_verification_attempts     = 0
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND id = $1
`

func (q *Queries) ClearPlayerVerificationCode(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, clearPlayerVerificationCode, id)
	return err
}

const createAnonymousPlayer = `-- name: CreateAnonymousPlayer :one
INSERT INTO project_players (tenant_id, project_id, external_id)
VALUES (
    current_setting('app.tenant_id', true)::bigint,
    $1,
    $2
)
RETURNING id, external_id, created_at
`

type CreateAnonymousPlayerParams struct {
	ProjectID  int64
	ExternalID string
}

type CreateAnonymousPlayerRow struct {
	ID         int64
	ExternalID string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateAnonymousPlayer(ctx context.Context, arg CreateAnonymousPlayerParams) (CreateAnonymousPlayerRow, error) {
	row := q.db.QueryRow(ctx, createAnonymousPlayer, arg.ProjectID, arg.ExternalID)
	var i CreateAnonymousPlayerRow
	err := row.Scan(&i.ID, &i.ExternalID, &i.CreatedAt)
	return i, err
}

const createEmailPlayer = `-- name: CreateEmailPlayer :one
INSERT INTO project_players (
    tenant_id, project_id, external_id, email, password_hash,
    email_verification_code_hash, email_verification_salt,
    email_verification_expires_at, email_verification_last_sent_at
)
VALUES (
    current_setting('app.tenant_id', true)::bigint,
    $1, $2, $3, $4, $5, $6, $7, now()
)
RETURNING id
`

type CreateEmailPlayerParams struct {
	ProjectID                  int64
	ExternalID                 string
	Email                      *string
	PasswordHash               []byte
	EmailVerificationCodeHash  []byte
	EmailVerificationSalt      []byte
	EmailVerificationExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateEmailPlayer(ctx context.Context, arg CreateEmailPlayerParams) (int64, error) {
	row := q.db.QueryRow(ctx, createEmailPlayer,
		arg.ProjectID,
		arg.ExternalID,
		arg.Email,
		arg.PasswordHash,
		arg.EmailVerificationCodeHash,
		arg.EmailVerificationSalt,
		arg.EmailVerificationExpiresAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (tenant_id, project_id, player_id, refresh_hash, expires_at)
VALUES (
    current_setting('app.tenant_id', true)::bigint,
    $1, $2, $3, $4
)
RETURNING id, created_at
`

type CreateSessionParams struct {
	ProjectID   int64
	PlayerID    int64
	RefreshHash []byte
	ExpiresAt   pgtype.Timestamptz
}

type CreateSessionRow struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ProjectID,
		arg.PlayerID,
		arg.RefreshHash,
		arg.ExpiresAt,
	)
	var i CreateSessionRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getPlayerByEmail = `-- name: GetPlayerByEmail :one
SELECT id, project_id, password_hash, email_verified_at
FROM project_players
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND project_id = $1
  AND email = $2
  AND deleted_at IS NULL
  AND disabled_at IS NULL
`

type GetPlayerByEmailParams struct {
	ProjectID int64
	Email     *string
}

type GetPlayerByEmailRow struct {
	ID              int64
	ProjectID       int64
	PasswordHash    []byte
	EmailVerifiedAt pgtype.Timestamptz
}

// Disabled accounts (disabled_at IS NOT NULL) are filtered out here so
// /v1/auth/login behaves identically to an unknown email — same dummy
// bcrypt + invalid_credentials response.
func (q *Queries) GetPlayerByEmail(ctx context.Context, arg GetPlayerByEmailParams) (GetPlayerByEmailRow, error) {
	row := q.db.QueryRow(ctx, getPlayerByEmail, arg.ProjectID, arg.Email)
	var i GetPlayerByEmailRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const getPlayerByExternalID = `-- name: GetPlayerByExternalID :one
SELECT id, project_id, email_verified_at
FROM project_players
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND project_id = $1
  AND external_id = $2
  AND deleted_at IS NULL
`

type GetPlayerByExternalIDParams struct {
	ProjectID  int64
	ExternalID string
}

type GetPlayerByExternalIDRow struct {
	ID              int64
	ProjectID       int64
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) GetPlayerByExternalID(ctx context.Context, arg GetPlayerByExternalIDParams) (GetPlayerByExternalIDRow, error) {
	row := q.db.QueryRow(ctx, getPlayerByExternalID, arg.ProjectID, arg.ExternalID)
	var i GetPlayerByExternalIDRow
	err := row.Scan(&i.ID, &i.ProjectID, &i.EmailVerifiedAt)
	return i, err
}

const getPlayerVerificationState = `-- name: GetPlayerVerificationState :one
SELECT
    id,
    email_verified_at,
    email_verification_code_hash,
    email_verification_salt,
    email_verification_expires_at,
    email_verification_attempts,
    email_verification_lifetime_attempts,
    email_verification_locked_until,
    email_verification_last_sent_at
FROM project_players
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND project_id = $1
  AND email = $2
  AND deleted_at IS NULL
`

type GetPlayerVerificationStateParams struct {
	ProjectID int64
	Email     *string
}

type GetPlayerVerificationStateRow struct {
	ID                                int64
	EmailVerifiedAt                   pgtype.Timestamptz
	EmailVerificationCodeHash         []byte
	EmailVerificationSalt             []byte
	EmailVerificationExpiresAt        pgtype.Timestamptz
	EmailVerificationAttempts         int32
	EmailVerificationLifetimeAttempts int32
	EmailVerificationLockedUntil      pgtype.Timestamptz
	EmailVerificationLastSentAt       pgtype.Timestamptz
}

func (q *Queries) GetPlayerVerificationState(ctx context.Context, arg GetPlayerVerificationStateParams) (GetPlayerVerificationStateRow, error) {
	row := q.db.QueryRow(ctx, getPlayerVerificationState, arg.ProjectID, arg.Email)
	var i GetPlayerVerificationStateRow
	err := row.Scan(
		&i.ID,
		&i.EmailVerifiedAt,
		&i.EmailVerificationCodeHash,
		&i.EmailVerificationSalt,
		&i.EmailVerificationExpiresAt,
		&i.EmailVerificationAttempts,
		&i.EmailVerificationLifetimeAttempts,
		&i.EmailVerificationLockedUntil,
		&i.EmailVerificationLastSentAt,
	)
	return i, err
}

const getSessionByRefreshHash = `-- name: GetSessionByRefreshHash :one
SELECT s.id, s.player_id, s.project_id, s.expires_at, s.revoked_at, s.revoked_reason
FROM sessions s
JOIN project_players u ON u.id = s.player_id
WHERE s.tenant_id = current_setting('app.tenant_id', true)::bigint
  AND s.project_id = $1
  AND s.refresh_hash = $2
  AND u.deleted_at IS NULL
  AND u.disabled_at IS NULL
`

type GetSessionByRefreshHashParams struct {
	ProjectID   int64
	RefreshHash []byte
}

type GetSessionByRefreshHashRow struct {
	ID            int64
	PlayerID      int64
	ProjectID     int64
	ExpiresAt     pgtype.Timestamptz
	RevokedAt     pgtype.Timestamptz
	RevokedReason *string
}

// Joined to project_players so refresh fails for disabled / deleted accounts
// even if the refresh token is still otherwise valid. revoked_reason lets the
// refresh handler tell a replayed *rotated* token (theft) from a logged-out one.
func (q *Queries) GetSessionByRefreshHash(ctx context.Context, arg GetSessionByRefreshHashParams) (GetSessionByRefreshHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshHash, arg.ProjectID, arg.RefreshHash)
	var i GetSessionByRefreshHashRow
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.ProjectID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const getTenantCustomTokenSecret = `-- name: GetTenantCustomTokenSecret :one
SELECT custom_token_secret
FROM tenants
WHERE id = current_setting('app.tenant_id', true)::bigint
`

func (q *Queries) GetTenantCustomTokenSecret(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, getTenantCustomTokenSecret)
	var custom_token_secret []byte
	err := row.Scan(&custom_token_secret)
	return custom_token_secret, err
}

const incrementPlayerVerificationAttempts = `-- name: IncrementPlayerVerificationAttempts :one
UPDATE project_players
SET email_verification_attempts = email_verification_attempts + 1
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND id = $1
RETURNING email_verification_attempts
`

func (q *Queries) IncrementPlayerVerificationAttempts(ctx context.Context, id int64) (int32, error) {
	row := q.db.QueryRow(ctx, incrementPlayerVerificationAttempts, id)
	var email_verification_attempts int32
	err := row.Scan(&email_verification_attempts)
	return email_verification_attempts, err
}

const lockPlayerVerification = `-- name: LockPlayerVerification :exec
UPDATE project_players
SET email_verification_locked_until = $1::timestamptz
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND id = $2
`

type LockPlayerVerificationParams struct {
	LockedUntil pgtype.Timestamptz
	ID          int64
}

func (q *Queries) LockPlayerVerification(ctx context.Context, arg LockPlayerVerificationParams) error {
	_, err := q.db.Exec(ctx, lockPlayerVerification, arg.LockedUntil, arg.ID)
	return err
}

const markPlayerVerified = `-- name: MarkPlayerVerified :exec
UPDATE project_players
SET email_verified_at               = now(),
    email_verification_code_hash    = NULL,
    email_verification_salt         = NULL,
    email_verification_expires_at   = NULL,
    email_verification_attempts     = 0
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND id = $1
`

func (q *Queries) MarkPlayerVerified(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markPlayerVerified, id)
	return err
}

const reservePlayerVerifyAttempt = `-- name: ReservePlayerVerifyAttempt :one
UPDATE project_players
SET email_verification_attempts = email_verification_attempts + 1,
    email_verification_lifetime_attempts = email_verification_lifetime_attempts + 1
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND id = $1
  AND email_verification_attempts < $2::int
RETURNING email_verification_attempts, email_verification_lifetime_attempts
`

type ReservePlayerVerifyAttemptParams struct {
	ID          int64
	MaxAttempts int32
}

type ReservePlayerVerifyAttemptRow struct {
	EmailVerificationAttempts         int32
	EmailVerificationLifetimeAttempts int32
}

// Atomic check-and-bump (see ReserveControlPanelVerifyAttempt for the
// TOCTOU explanation). Returns 0 rows when already at cap.
func (q *Queries) ReservePlayerVerifyAttempt(ctx context.Context, arg ReservePlayerVerifyAttemptParams) (ReservePlayerVerifyAttemptRow, error) {
	row := q.db.QueryRow(ctx, reservePlayerVerifyAttempt, arg.ID, arg.MaxAttempts)
	var i ReservePlayerVerifyAttemptRow
	err := row.Scan(&i.EmailVerificationAttempts, &i.EmailVerificationLifetimeAttempts)
	return i, err
}

const revokeActivePlayerSessions = `-- name: RevokeActivePlayerSessions :execrows
UPDATE sessions
SET revoked_at = now(), revoked_reason = 'reuse_detected'
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND project_id = $1
  AND player_id = $2
  AND revoked_at IS NULL
`

type RevokeActivePlayerSessionsParams struct {
	ProjectID int64
	PlayerID  int64
}

// Reuse-detection response: nuke every live session for the player in this
// project. Paired with BumpPlayerSessionEpoch so outstanding access tokens die
// at the epoch gate immediately, not just at TTL.
func (q *Queries) RevokeActivePlayerSessions(ctx context.Context, arg RevokeActivePlayerSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeActivePlayerSessions, arg.ProjectID, arg.PlayerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE sessions
SET revoked_at = now(), revoked_reason = 'rotated'
WHERE id = $1
  AND tenant_id = current_setting('app.tenant_id', true)::bigint
  AND revoked_at IS NULL
`

// Rotation path: the token is being superseded by a freshly-issued one, so a
// later replay of this hash is a reuse (theft) signal.
func (q *Queries) RevokeSession(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSessionByRefreshHash = `-- name: RevokeSessionByRefreshHash :one
UPDATE sessions
SET revoked_at = now(), revoked_reason = 'logout'
WHERE refresh_hash = $1
  AND tenant_id = current_setting('app.tenant_id', true)::bigint
  AND revoked_at IS NULL
RETURNING player_id
`

// Logout path: a later replay of this hash is a benign stale-client retry, not
// reuse, so it must NOT trip the family kill.
func (q *Queries) RevokeSessionByRefreshHash(ctx context.Context, refreshHash []byte) (int64, error) {
	row := q.db.QueryRow(ctx, revokeSessionByRefreshHash, refreshHash)
	var player_id int64
	err := row.Scan(&player_id)
	return player_id, err
}

const setPlayerVerificationCode = `-- name: SetPlayerVerificationCode :exec
UPDATE project_players
SET email_verification_code_hash    = $3,
    email_verification_salt         = $4,
    email_verification_expires_at   = $5,
    email_verification_attempts     = 0,
    email_verification_last_sent_at = now()
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND project_id = $1
  AND id = $2
`

type SetPlayerVerificationCodeParams struct {
	ProjectID                  int64
	ID                         int64
	EmailVerificationCodeHash  []byte
	EmailVerificationSalt      []byte
	EmailVerificationExpiresAt pgtype.Timestamptz
}

func (q *Queries) SetPlayerVerificationCode(ctx context.Context, arg SetPlayerVerificationCodeParams) error {
	_, err := q.db.Exec(ctx, setPlayerVerificationCode,
		arg.ProjectID,
		arg.ID,
		arg.EmailVerificationCodeHash,
		arg.EmailVerificationSalt,
		arg.EmailVerificationExpiresAt,
	)
	return err
}

const upsertPlayerByExternalID = `-- name: UpsertPlayerByExternalID :one
INSERT INTO project_players (tenant_id, project_id, external_id)
VALUES (
    current_setting('app.tenant_id', true)::bigint,
    $1, $2
)
ON CONFLICT (tenant_id, project_id, external_id)
    WHERE deleted_at IS NULL
DO UPDATE SET external_id = EXCLUDED.external_id
RETURNING id
`

type UpsertPlayerByExternalIDParams struct {
	ProjectID  int64
	ExternalID string
}

// Custom-token flow: find existing player with this external_id under
// (tenant, project) or create one. Idempotent across repeated calls.
func (q *Queries) UpsertPlayerByExternalID(ctx context.Context, arg UpsertPlayerByExternalIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertPlayerByExternalID, arg.ProjectID, arg.ExternalID)
	var id int64
	err := row.Scan(&id)
	return id, err
}
