// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: change_requests.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveTenantChangeRequest = `-- name: ApproveTenantChangeRequest :execrows
UPDATE tenant_change_requests
SET status = 'approved',
    reviewed_by_user_id = $2,
    reviewed_at = now()
WHERE id = $1 AND status = 'pending'
`

type ApproveTenantChangeRequestParams struct {
	ID         int64
	ReviewedBy *int64
}

func (q *Queries) ApproveTenantChangeRequest(ctx context.Context, arg ApproveTenantChangeRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, approveTenantChangeRequest, arg.ID, arg.ReviewedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createTenantChangeRequest = `-- name: CreateTenantChangeRequest :one
INSERT INTO tenant_change_requests (tenant_id, requested_by_user_id, kind, requested_tier, feature, note)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateTenantChangeRequestParams struct {
	TenantID          int64
	RequestedByUserID *int64
	Kind              string
	RequestedTier     *int16
	Feature           *string
	Note              string
}

// Submit a tenant change request. The pending-unique index rejects a second
// open request of the same kind/feature (surfaced as a friendly message).
func (q *Queries) CreateTenantChangeRequest(ctx context.Context, arg CreateTenantChangeRequestParams) (int64, error) {
	row := q.db.QueryRow(ctx, createTenantChangeRequest,
		arg.TenantID,
		arg.RequestedByUserID,
		arg.Kind,
		arg.RequestedTier,
		arg.Feature,
		arg.Note,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const denyTenantChangeRequest = `-- name: DenyTenantChangeRequest :execrows
UPDATE tenant_change_requests
SET status = 'denied',
    reviewed_by_user_id = $2,
    reviewed_at = now(),
    review_reason = $3
WHERE id = $1 AND status = 'pending'
`

type DenyTenantChangeRequestParams struct {
	ID           int64
	ReviewedBy   *int64
	ReviewReason *string
}

func (q *Queries) DenyTenantChangeRequest(ctx context.Context, arg DenyTenantChangeRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, denyTenantChangeRequest, arg.ID, arg.ReviewedBy, arg.ReviewReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTenantChangeRequestByID = `-- name: GetTenantChangeRequestByID :one
SELECT id, tenant_id, kind, requested_tier, feature, note, status
FROM tenant_change_requests
WHERE id = $1
`

type GetTenantChangeRequestByIDRow struct {
	ID            int64
	TenantID      int64
	Kind          string
	RequestedTier *int16
	Feature       *string
	Note          string
	Status        string
}

func (q *Queries) GetTenantChangeRequestByID(ctx context.Context, id int64) (GetTenantChangeRequestByIDRow, error) {
	row := q.db.QueryRow(ctx, getTenantChangeRequestByID, id)
	var i GetTenantChangeRequestByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Kind,
		&i.RequestedTier,
		&i.Feature,
		&i.Note,
		&i.Status,
	)
	return i, err
}

const listPendingTenantChangeRequests = `-- name: ListPendingTenantChangeRequests :many
SELECT r.id, r.tenant_id, t.name AS tenant_name, t.tier AS current_tier,
       r.kind, r.requested_tier, r.feature, r.note, r.created_at
FROM tenant_change_requests r
JOIN tenants t ON t.id = r.tenant_id
WHERE r.status = 'pending'
  AND t.deleted_at IS NULL
ORDER BY r.created_at ASC
`

type ListPendingTenantChangeRequestsRow struct {
	ID            int64
	TenantID      int64
	TenantName    string
	CurrentTier   int16
	Kind          string
	RequestedTier *int16
	Feature       *string
	Note          string
	CreatedAt     pgtype.Timestamptz
}

// Platform-admin review queue: pending requests with tenant name + current
// class. Read cross-tenant (bootstrap tx).
func (q *Queries) ListPendingTenantChangeRequests(ctx context.Context) ([]ListPendingTenantChangeRequestsRow, error) {
	rows, err := q.db.Query(ctx, listPendingTenantChangeRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingTenantChangeRequestsRow
	for rows.Next() {
		var i ListPendingTenantChangeRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TenantName,
			&i.CurrentTier,
			&i.Kind,
			&i.RequestedTier,
			&i.Feature,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantChangeRequests = `-- name: ListTenantChangeRequests :many
SELECT id, kind, requested_tier, feature, note, status, review_reason, created_at, reviewed_at
FROM tenant_change_requests
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT 50
`

type ListTenantChangeRequestsRow struct {
	ID            int64
	Kind          string
	RequestedTier *int16
	Feature       *string
	Note          string
	Status        string
	ReviewReason  *string
	CreatedAt     pgtype.Timestamptz
	ReviewedAt    pgtype.Timestamptz
}

// The tenant's own requests (any status) for the settings page. Filters by
// explicit tenant_id (the table has no RLS).
func (q *Queries) ListTenantChangeRequests(ctx context.Context, tenantID int64) ([]ListTenantChangeRequestsRow, error) {
	rows, err := q.db.Query(ctx, listTenantChangeRequests, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTenantChangeRequestsRow
	for rows.Next() {
		var i ListTenantChangeRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.RequestedTier,
			&i.Feature,
			&i.Note,
			&i.Status,
			&i.ReviewReason,
			&i.CreatedAt,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantEnabledFeatures = `-- name: ListTenantEnabledFeatures :many
SELECT feature
FROM feature_grants
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND project_id IS NULL
  AND enabled = true
`

// Tenant-level features the tenant already holds, to exclude from the request
// dropdown. Reads feature_grants in tenant RLS context.
func (q *Queries) ListTenantEnabledFeatures(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listTenantEnabledFeatures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var feature string
		if err := rows.Scan(&feature); err != nil {
			return nil, err
		}
		items = append(items, feature)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTenantTierIfUpgrade = `-- name: SetTenantTierIfUpgrade :execrows
UPDATE tenants
SET tier = $1
WHERE id = current_setting('app.tenant_id', true)::bigint
  AND tier < $1
`

// Auto-applied on tier-upgrade approval. The direction check and write are one
// atomic operation so a stale request can never lower the current tier.
func (q *Queries) SetTenantTierIfUpgrade(ctx context.Context, tier int16) (int64, error) {
	result, err := q.db.Exec(ctx, setTenantTierIfUpgrade, tier)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertTenantFeatureGrant = `-- name: UpsertTenantFeatureGrant :exec
INSERT INTO feature_grants (tenant_id, project_id, feature, enabled, approved_by_control_panel_user_id, reason)
VALUES (current_setting('app.tenant_id', true)::bigint, NULL, $1, true,
        $2, $3)
ON CONFLICT (tenant_id, COALESCE(project_id, 0), feature)
DO UPDATE SET enabled = true,
              approved_by_control_panel_user_id = EXCLUDED.approved_by_control_panel_user_id,
              reason = EXCLUDED.reason,
              updated_at = now()
`

type UpsertTenantFeatureGrantParams struct {
	Feature    string
	ApprovedBy *int64
	Reason     *string
}

// Auto-applied on feature-request approval. Tenant-level grant (project_id
// NULL); runs in tenant RLS context.
func (q *Queries) UpsertTenantFeatureGrant(ctx context.Context, arg UpsertTenantFeatureGrantParams) error {
	_, err := q.db.Exec(ctx, upsertTenantFeatureGrant, arg.Feature, arg.ApprovedBy, arg.Reason)
	return err
}
