// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connection_limit_overrides.sql

package sqlcgen

import (
	"context"
)

const deleteConnectionLimitOverride = `-- name: DeleteConnectionLimitOverride :execrows
DELETE FROM connection_limit_overrides
WHERE tenant_id = $1
`

func (q *Queries) DeleteConnectionLimitOverride(ctx context.Context, tenantID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConnectionLimitOverride, tenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConnectionLimitOverride = `-- name: GetConnectionLimitOverride :one
SELECT sustained, ceiling
FROM connection_limit_overrides
WHERE tenant_id = $1
`

type GetConnectionLimitOverrideRow struct {
	Sustained int64
	Ceiling   int64
}

// Tenant-level realtime admission envelope. The WebSocket admission path falls
// back to compiled tier defaults when no row exists.
func (q *Queries) GetConnectionLimitOverride(ctx context.Context, tenantID int64) (GetConnectionLimitOverrideRow, error) {
	row := q.db.QueryRow(ctx, getConnectionLimitOverride, tenantID)
	var i GetConnectionLimitOverrideRow
	err := row.Scan(&i.Sustained, &i.Ceiling)
	return i, err
}

const upsertConnectionLimitOverride = `-- name: UpsertConnectionLimitOverride :exec
INSERT INTO connection_limit_overrides (tenant_id, sustained, ceiling, updated_by, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (tenant_id)
DO UPDATE SET sustained = EXCLUDED.sustained,
              ceiling = EXCLUDED.ceiling,
              updated_by = EXCLUDED.updated_by,
              updated_at = now()
`

type UpsertConnectionLimitOverrideParams struct {
	TenantID  int64
	Sustained int64
	Ceiling   int64
	UpdatedBy *int64
}

func (q *Queries) UpsertConnectionLimitOverride(ctx context.Context, arg UpsertConnectionLimitOverrideParams) error {
	_, err := q.db.Exec(ctx, upsertConnectionLimitOverride,
		arg.TenantID,
		arg.Sustained,
		arg.Ceiling,
		arg.UpdatedBy,
	)
	return err
}
