// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: control_panel_users.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpControlPanelLoginFailure = `-- name: BumpControlPanelLoginFailure :one
UPDATE control_panel_users
SET login_failures = login_failures + 1,
    locked_until = CASE
        WHEN login_failures + 1 >= $1::int
            THEN $2::timestamptz
        ELSE locked_until
    END
WHERE id = $3
RETURNING login_failures, locked_until
`

type BumpControlPanelLoginFailureParams struct {
	FailureLimit int32
	LockoutUntil pgtype.Timestamptz
	ID           int64
}

type BumpControlPanelLoginFailureRow struct {
	LoginFailures int32
	LockedUntil   pgtype.Timestamptz
}

// Atomic increment + conditional lockout. The previous read-then-write
// pattern was TOCTOU-racy: N parallel failed logins all read the same value
// and wrote N+1, so 10 simultaneous wrong passwords landed at login_failures=1
// and the lockout never fired. UPDATE...RETURNING serialises under the row
// lock pgx already takes.
func (q *Queries) BumpControlPanelLoginFailure(ctx context.Context, arg BumpControlPanelLoginFailureParams) (BumpControlPanelLoginFailureRow, error) {
	row := q.db.QueryRow(ctx, bumpControlPanelLoginFailure, arg.FailureLimit, arg.LockoutUntil, arg.ID)
	var i BumpControlPanelLoginFailureRow
	err := row.Scan(&i.LoginFailures, &i.LockedUntil)
	return i, err
}

const clearControlPanelVerificationCode = `-- name: ClearControlPanelVerificationCode :exec
UPDATE control_panel_users
SET email_verification_code_hash    = NULL,
    email_verification_salt         = NULL,
    email_verification_expires_at   = NULL,
    email_verification_attempts     = 0
WHERE id = $1
`

func (q *Queries) ClearControlPanelVerificationCode(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, clearControlPanelVerificationCode, id)
	return err
}

const countControlPanelUsers = `-- name: CountControlPanelUsers :one
SELECT count(*)::bigint FROM control_panel_users
`

func (q *Queries) CountControlPanelUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countControlPanelUsers)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countControlPanelUsersForPlatformAdmin = `-- name: CountControlPanelUsersForPlatformAdmin :one
SELECT COUNT(*)::bigint
FROM control_panel_users u
WHERE ($1::text IS NULL OR u.email::text ILIKE '%' || $1::text || '%')
`

func (q *Queries) CountControlPanelUsersForPlatformAdmin(ctx context.Context, emailFilter *string) (int64, error) {
	row := q.db.QueryRow(ctx, countControlPanelUsersForPlatformAdmin, emailFilter)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countEnabledPlatformAdmins = `-- name: CountEnabledPlatformAdmins :one
SELECT COUNT(*)::bigint
FROM control_panel_users
WHERE is_platform_admin = true
  AND disabled_at IS NULL
`

func (q *Queries) CountEnabledPlatformAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEnabledPlatformAdmins)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createControlPanelSession = `-- name: CreateControlPanelSession :one
INSERT INTO control_panel_sessions (
    control_panel_user_id, refresh_hash, csrf_secret, expires_at, ip, user_agent
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, expires_at, created_at
`

type CreateControlPanelSessionParams struct {
	ControlPanelUserID int64
	RefreshHash        []byte
	CsrfSecret         []byte
	ExpiresAt          pgtype.Timestamptz
	Ip                 *string
	UserAgent          *string
}

type CreateControlPanelSessionRow struct {
	ID        int64
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateControlPanelSession(ctx context.Context, arg CreateControlPanelSessionParams) (CreateControlPanelSessionRow, error) {
	row := q.db.QueryRow(ctx, createControlPanelSession,
		arg.ControlPanelUserID,
		arg.RefreshHash,
		arg.CsrfSecret,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	var i CreateControlPanelSessionRow
	err := row.Scan(&i.ID, &i.ExpiresAt, &i.CreatedAt)
	return i, err
}

const createControlPanelUser = `-- name: CreateControlPanelUser :one
INSERT INTO control_panel_users (email, password_hash, is_platform_admin)
VALUES ($1, $2, $3)
RETURNING id, email::text AS email, is_platform_admin, created_at
`

type CreateControlPanelUserParams struct {
	Email           string
	PasswordHash    []byte
	IsPlatformAdmin bool
}

type CreateControlPanelUserRow struct {
	ID              int64
	Email           string
	IsPlatformAdmin bool
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) CreateControlPanelUser(ctx context.Context, arg CreateControlPanelUserParams) (CreateControlPanelUserRow, error) {
	row := q.db.QueryRow(ctx, createControlPanelUser, arg.Email, arg.PasswordHash, arg.IsPlatformAdmin)
	var i CreateControlPanelUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.IsPlatformAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const createFirstControlPanelAdmin = `-- name: CreateFirstControlPanelAdmin :one
INSERT INTO control_panel_users (email, password_hash, is_platform_admin)
SELECT $1, $2, true
WHERE NOT EXISTS (SELECT 1 FROM control_panel_users)
RETURNING id, email::text AS email, is_platform_admin, created_at
`

type CreateFirstControlPanelAdminParams struct {
	Email        string
	PasswordHash []byte
}

type CreateFirstControlPanelAdminRow struct {
	ID              int64
	Email           string
	IsPlatformAdmin bool
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) CreateFirstControlPanelAdmin(ctx context.Context, arg CreateFirstControlPanelAdminParams) (CreateFirstControlPanelAdminRow, error) {
	row := q.db.QueryRow(ctx, createFirstControlPanelAdmin, arg.Email, arg.PasswordHash)
	var i CreateFirstControlPanelAdminRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.IsPlatformAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const createVerifiedControlPanelUser = `-- name: CreateVerifiedControlPanelUser :one
INSERT INTO control_panel_users (
    email, password_hash, is_platform_admin, email_verified_at
)
VALUES (
    $1,
    $2,
    $3,
    now()
)
RETURNING id, email::text AS email, is_platform_admin, created_at
`

type CreateVerifiedControlPanelUserParams struct {
	Email           string
	PasswordHash    []byte
	IsPlatformAdmin bool
}

type CreateVerifiedControlPanelUserRow struct {
	ID              int64
	Email           string
	IsPlatformAdmin bool
	CreatedAt       pgtype.Timestamptz
}

// Used by invite acceptance: creates a new user who is verified by
// definition (they had to click the invite link in their inbox).
func (q *Queries) CreateVerifiedControlPanelUser(ctx context.Context, arg CreateVerifiedControlPanelUserParams) (CreateVerifiedControlPanelUserRow, error) {
	row := q.db.QueryRow(ctx, createVerifiedControlPanelUser, arg.Email, arg.PasswordHash, arg.IsPlatformAdmin)
	var i CreateVerifiedControlPanelUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.IsPlatformAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getControlPanelMembership = `-- name: GetControlPanelMembership :one
SELECT id, role
FROM control_panel_memberships
WHERE control_panel_user_id = $1
  AND tenant_id = $2
`

type GetControlPanelMembershipParams struct {
	ControlPanelUserID int64
	TenantID           int64
}

type GetControlPanelMembershipRow struct {
	ID   int64
	Role string
}

func (q *Queries) GetControlPanelMembership(ctx context.Context, arg GetControlPanelMembershipParams) (GetControlPanelMembershipRow, error) {
	row := q.db.QueryRow(ctx, getControlPanelMembership, arg.ControlPanelUserID, arg.TenantID)
	var i GetControlPanelMembershipRow
	err := row.Scan(&i.ID, &i.Role)
	return i, err
}

const getControlPanelSessionByRefreshHash = `-- name: GetControlPanelSessionByRefreshHash :one
SELECT
    s.id,
    s.control_panel_user_id,
    s.csrf_secret,
    s.expires_at,
    s.revoked_at,
    s.created_at,
    u.email::text AS email,
    u.is_platform_admin
FROM control_panel_sessions s
JOIN control_panel_users u ON u.id = s.control_panel_user_id
WHERE s.refresh_hash = $1
  AND u.disabled_at IS NULL
`

type GetControlPanelSessionByRefreshHashRow struct {
	ID                 int64
	ControlPanelUserID int64
	CsrfSecret         []byte
	ExpiresAt          pgtype.Timestamptz
	RevokedAt          pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	Email              string
	IsPlatformAdmin    bool
}

// Joined to control_panel_users so the session dies as soon as a platform
// admin sets disabled_at, without needing a separate session-purge step
// on every request path. requireSession maps ErrNoRows to a redirect to
// /login, which is what we want for disabled accounts.
func (q *Queries) GetControlPanelSessionByRefreshHash(ctx context.Context, refreshHash []byte) (GetControlPanelSessionByRefreshHashRow, error) {
	row := q.db.QueryRow(ctx, getControlPanelSessionByRefreshHash, refreshHash)
	var i GetControlPanelSessionByRefreshHashRow
	err := row.Scan(
		&i.ID,
		&i.ControlPanelUserID,
		&i.CsrfSecret,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.Email,
		&i.IsPlatformAdmin,
	)
	return i, err
}

const getControlPanelUserAnyStatusByEmail = `-- name: GetControlPanelUserAnyStatusByEmail :one
SELECT
    id,
    email::text AS email,
    password_hash,
    is_platform_admin,
    disabled_at
FROM control_panel_users
WHERE email = $1
`

type GetControlPanelUserAnyStatusByEmailRow struct {
	ID              int64
	Email           string
	PasswordHash    []byte
	IsPlatformAdmin bool
	DisabledAt      pgtype.Timestamptz
}

// Status-blind variant used ONLY by the invite-accept code path so we
// can distinguish "no row" (truly new email — create user) from "row
// exists but disabled" (refuse with errInviteForDisabledAccount).
// DO NOT use this for authentication.
func (q *Queries) GetControlPanelUserAnyStatusByEmail(ctx context.Context, email string) (GetControlPanelUserAnyStatusByEmailRow, error) {
	row := q.db.QueryRow(ctx, getControlPanelUserAnyStatusByEmail, email)
	var i GetControlPanelUserAnyStatusByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IsPlatformAdmin,
		&i.DisabledAt,
	)
	return i, err
}

const getControlPanelUserByEmail = `-- name: GetControlPanelUserByEmail :one
SELECT
    id,
    email::text AS email,
    password_hash,
    is_platform_admin,
    login_failures,
    locked_until,
    last_login_at,
    email_verified_at,
    created_at
FROM control_panel_users
WHERE email = $1
  AND disabled_at IS NULL
`

type GetControlPanelUserByEmailRow struct {
	ID              int64
	Email           string
	PasswordHash    []byte
	IsPlatformAdmin bool
	LoginFailures   int32
	LockedUntil     pgtype.Timestamptz
	LastLoginAt     pgtype.Timestamptz
	EmailVerifiedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

// Disabled accounts (disabled_at IS NOT NULL) are filtered out here so
// /v1/control-panel/login behaves identically to an unknown email — same
// dummy bcrypt + invalid_credentials response.
func (q *Queries) GetControlPanelUserByEmail(ctx context.Context, email string) (GetControlPanelUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getControlPanelUserByEmail, email)
	var i GetControlPanelUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IsPlatformAdmin,
		&i.LoginFailures,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getControlPanelUserByID = `-- name: GetControlPanelUserByID :one
SELECT
    id,
    email::text AS email,
    is_platform_admin,
    created_at
FROM control_panel_users
WHERE id = $1
`

type GetControlPanelUserByIDRow struct {
	ID              int64
	Email           string
	IsPlatformAdmin bool
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) GetControlPanelUserByID(ctx context.Context, id int64) (GetControlPanelUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getControlPanelUserByID, id)
	var i GetControlPanelUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.IsPlatformAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getControlPanelUserVerificationState = `-- name: GetControlPanelUserVerificationState :one
SELECT
    id,
    email::text AS email,
    email_verified_at,
    email_verification_code_hash,
    email_verification_salt,
    email_verification_expires_at,
    email_verification_attempts,
    email_verification_lifetime_attempts,
    email_verification_locked_until,
    email_verification_last_sent_at
FROM control_panel_users
WHERE id = $1
`

type GetControlPanelUserVerificationStateRow struct {
	ID                                int64
	Email                             string
	EmailVerifiedAt                   pgtype.Timestamptz
	EmailVerificationCodeHash         []byte
	EmailVerificationSalt             []byte
	EmailVerificationExpiresAt        pgtype.Timestamptz
	EmailVerificationAttempts         int32
	EmailVerificationLifetimeAttempts int32
	EmailVerificationLockedUntil      pgtype.Timestamptz
	EmailVerificationLastSentAt       pgtype.Timestamptz
}

func (q *Queries) GetControlPanelUserVerificationState(ctx context.Context, id int64) (GetControlPanelUserVerificationStateRow, error) {
	row := q.db.QueryRow(ctx, getControlPanelUserVerificationState, id)
	var i GetControlPanelUserVerificationStateRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.EmailVerificationCodeHash,
		&i.EmailVerificationSalt,
		&i.EmailVerificationExpiresAt,
		&i.EmailVerificationAttempts,
		&i.EmailVerificationLifetimeAttempts,
		&i.EmailVerificationLockedUntil,
		&i.EmailVerificationLastSentAt,
	)
	return i, err
}

const incrementControlPanelVerificationAttempts = `-- name: IncrementControlPanelVerificationAttempts :one
UPDATE control_panel_users
SET email_verification_attempts = email_verification_attempts + 1
WHERE id = $1
RETURNING email_verification_attempts
`

func (q *Queries) IncrementControlPanelVerificationAttempts(ctx context.Context, id int64) (int32, error) {
	row := q.db.QueryRow(ctx, incrementControlPanelVerificationAttempts, id)
	var email_verification_attempts int32
	err := row.Scan(&email_verification_attempts)
	return email_verification_attempts, err
}

const listControlPanelTenantsForPlatformAdmin = `-- name: ListControlPanelTenantsForPlatformAdmin :many
SELECT
    t.id,
    t.name,
    'owner'::text AS role,
    t.created_at
FROM tenants t
WHERE t.deleted_at IS NULL
ORDER BY t.id DESC
`

type ListControlPanelTenantsForPlatformAdminRow struct {
	ID        int64
	Name      string
	Role      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListControlPanelTenantsForPlatformAdmin(ctx context.Context) ([]ListControlPanelTenantsForPlatformAdminRow, error) {
	rows, err := q.db.Query(ctx, listControlPanelTenantsForPlatformAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListControlPanelTenantsForPlatformAdminRow
	for rows.Next() {
		var i ListControlPanelTenantsForPlatformAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listControlPanelTenantsForUser = `-- name: ListControlPanelTenantsForUser :many
SELECT
    t.id,
    t.name,
    m.role,
    t.created_at
FROM control_panel_memberships m
JOIN tenants t ON t.id = m.tenant_id
WHERE m.control_panel_user_id = $1
  AND t.deleted_at IS NULL
ORDER BY t.id DESC
`

type ListControlPanelTenantsForUserRow struct {
	ID        int64
	Name      string
	Role      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListControlPanelTenantsForUser(ctx context.Context, controlPanelUserID int64) ([]ListControlPanelTenantsForUserRow, error) {
	rows, err := q.db.Query(ctx, listControlPanelTenantsForUser, controlPanelUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListControlPanelTenantsForUserRow
	for rows.Next() {
		var i ListControlPanelTenantsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listControlPanelUsersForPlatformAdmin = `-- name: ListControlPanelUsersForPlatformAdmin :many
SELECT
    u.id,
    u.email::text AS email,
    u.is_platform_admin,
    u.disabled_at,
    u.last_login_at,
    u.created_at,
    (SELECT COUNT(*)::bigint FROM control_panel_memberships m WHERE m.control_panel_user_id = u.id) AS tenant_count
FROM control_panel_users u
WHERE ($1::text IS NULL OR u.email::text ILIKE '%' || $1::text || '%')
ORDER BY u.created_at DESC
LIMIT $3 OFFSET $2
`

type ListControlPanelUsersForPlatformAdminParams struct {
	EmailFilter *string
	Off         int32
	Lim         int32
}

type ListControlPanelUsersForPlatformAdminRow struct {
	ID              int64
	Email           string
	IsPlatformAdmin bool
	DisabledAt      pgtype.Timestamptz
	LastLoginAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	TenantCount     int64
}

// Powers the /v1/control-panel/admin/users page. tenant_count is a
// correlated subquery so users with zero memberships still appear.
func (q *Queries) ListControlPanelUsersForPlatformAdmin(ctx context.Context, arg ListControlPanelUsersForPlatformAdminParams) ([]ListControlPanelUsersForPlatformAdminRow, error) {
	rows, err := q.db.Query(ctx, listControlPanelUsersForPlatformAdmin, arg.EmailFilter, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListControlPanelUsersForPlatformAdminRow
	for rows.Next() {
		var i ListControlPanelUsersForPlatformAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.IsPlatformAdmin,
			&i.DisabledAt,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.TenantCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockControlPanelUserVerification = `-- name: LockControlPanelUserVerification :exec
UPDATE control_panel_users
SET email_verification_locked_until = $1::timestamptz
WHERE id = $2
`

type LockControlPanelUserVerificationParams struct {
	LockedUntil pgtype.Timestamptz
	ID          int64
}

// Set the lockout window on an account that just tipped over
// MaxLifetimeAttempts. The Go side computes the timestamp so the lockout
// duration stays a single source of truth.
func (q *Queries) LockControlPanelUserVerification(ctx context.Context, arg LockControlPanelUserVerificationParams) error {
	_, err := q.db.Exec(ctx, lockControlPanelUserVerification, arg.LockedUntil, arg.ID)
	return err
}

const lockEnabledPlatformAdmins = `-- name: LockEnabledPlatformAdmins :many
SELECT id
FROM control_panel_users
WHERE is_platform_admin = true
  AND disabled_at IS NULL
ORDER BY id
FOR UPDATE
`

// Serializes last-admin checks by locking the currently enabled platform
// admin rows before counting them in the surrounding transaction.
func (q *Queries) LockEnabledPlatformAdmins(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, lockEnabledPlatformAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markControlPanelUserVerified = `-- name: MarkControlPanelUserVerified :exec
UPDATE control_panel_users
SET email_verified_at               = now(),
    email_verification_code_hash    = NULL,
    email_verification_salt         = NULL,
    email_verification_expires_at   = NULL,
    email_verification_attempts     = 0
WHERE id = $1
`

func (q *Queries) MarkControlPanelUserVerified(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markControlPanelUserVerified, id)
	return err
}

const recordControlPanelLoginSuccess = `-- name: RecordControlPanelLoginSuccess :exec
UPDATE control_panel_users
SET login_failures = 0,
    locked_until = NULL,
    last_login_at = now()
WHERE id = $1
`

func (q *Queries) RecordControlPanelLoginSuccess(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, recordControlPanelLoginSuccess, id)
	return err
}

const reserveControlPanelVerifyAttempt = `-- name: ReserveControlPanelVerifyAttempt :one
UPDATE control_panel_users
SET email_verification_attempts = email_verification_attempts + 1,
    email_verification_lifetime_attempts = email_verification_lifetime_attempts + 1
WHERE id = $1
  AND email_verification_attempts < $2::int
RETURNING email_verification_attempts, email_verification_lifetime_attempts
`

type ReserveControlPanelVerifyAttemptParams struct {
	ID          int64
	MaxAttempts int32
}

type ReserveControlPanelVerifyAttemptRow struct {
	EmailVerificationAttempts         int32
	EmailVerificationLifetimeAttempts int32
}

// Atomic check-and-bump used in place of the previous fetch-then-increment
// pattern: two parallel wrong codes used to both pass the cap check before
// either incremented, so the lockout could be overshot. The WHERE clause
// now folds the bound into the same statement that mutates the counter.
// Returns 0 rows when already at cap (caller treats as errVerifyLocked).
func (q *Queries) ReserveControlPanelVerifyAttempt(ctx context.Context, arg ReserveControlPanelVerifyAttemptParams) (ReserveControlPanelVerifyAttemptRow, error) {
	row := q.db.QueryRow(ctx, reserveControlPanelVerifyAttempt, arg.ID, arg.MaxAttempts)
	var i ReserveControlPanelVerifyAttemptRow
	err := row.Scan(&i.EmailVerificationAttempts, &i.EmailVerificationLifetimeAttempts)
	return i, err
}

const revokeAllControlPanelSessionsForUser = `-- name: RevokeAllControlPanelSessionsForUser :exec
UPDATE control_panel_sessions
SET revoked_at = now()
WHERE control_panel_user_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAllControlPanelSessionsForUser(ctx context.Context, controlPanelUserID int64) error {
	_, err := q.db.Exec(ctx, revokeAllControlPanelSessionsForUser, controlPanelUserID)
	return err
}

const revokeControlPanelSession = `-- name: RevokeControlPanelSession :exec
UPDATE control_panel_sessions
SET revoked_at = now()
WHERE id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeControlPanelSession(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, revokeControlPanelSession, id)
	return err
}

const revokeOpenInvitationsByInviter = `-- name: RevokeOpenInvitationsByInviter :exec
UPDATE control_panel_invitations
SET revoked_at = now()
WHERE invited_by_user_id = $1
  AND accepted_at IS NULL
  AND revoked_at IS NULL
`

// Bulk-revoke the outgoing invitations a (now-disabled) user created.
// Re-enabling does NOT un-revoke these; the platform admin can re-issue.
func (q *Queries) RevokeOpenInvitationsByInviter(ctx context.Context, invitedByUserID int64) error {
	_, err := q.db.Exec(ctx, revokeOpenInvitationsByInviter, invitedByUserID)
	return err
}

const setControlPanelUserDisabled = `-- name: SetControlPanelUserDisabled :exec
UPDATE control_panel_users
SET disabled_at = $1::timestamptz
WHERE id = $2
`

type SetControlPanelUserDisabledParams struct {
	DisabledAt pgtype.Timestamptz
	ID         int64
}

// Nullable timestamptz so the same query handles disable (now()) and
// enable (NULL).
func (q *Queries) SetControlPanelUserDisabled(ctx context.Context, arg SetControlPanelUserDisabledParams) error {
	_, err := q.db.Exec(ctx, setControlPanelUserDisabled, arg.DisabledAt, arg.ID)
	return err
}

const setControlPanelUserVerificationCode = `-- name: SetControlPanelUserVerificationCode :exec
UPDATE control_panel_users
SET email_verification_code_hash    = $1,
    email_verification_salt         = $2,
    email_verification_expires_at   = $3,
    email_verification_attempts     = 0,
    email_verification_last_sent_at = now()
WHERE id = $4
`

type SetControlPanelUserVerificationCodeParams struct {
	CodeHash  []byte
	CodeSalt  []byte
	ExpiresAt pgtype.Timestamptz
	ID        int64
}

func (q *Queries) SetControlPanelUserVerificationCode(ctx context.Context, arg SetControlPanelUserVerificationCodeParams) error {
	_, err := q.db.Exec(ctx, setControlPanelUserVerificationCode,
		arg.CodeHash,
		arg.CodeSalt,
		arg.ExpiresAt,
		arg.ID,
	)
	return err
}

const touchControlPanelSession = `-- name: TouchControlPanelSession :exec
UPDATE control_panel_sessions
SET last_seen_at = now(),
    expires_at = LEAST($1::timestamptz, created_at + interval '7 days')
WHERE id = $2
  AND revoked_at IS NULL
`

type TouchControlPanelSessionParams struct {
	ExpiresAt pgtype.Timestamptz
	ID        int64
}

func (q *Queries) TouchControlPanelSession(ctx context.Context, arg TouchControlPanelSessionParams) error {
	_, err := q.db.Exec(ctx, touchControlPanelSession, arg.ExpiresAt, arg.ID)
	return err
}

const updateControlPanelPassword = `-- name: UpdateControlPanelPassword :exec
UPDATE control_panel_users
SET password_hash = $1,
    login_failures = 0,
    locked_until = NULL
WHERE id = $2
`

type UpdateControlPanelPasswordParams struct {
	PasswordHash []byte
	ID           int64
}

func (q *Queries) UpdateControlPanelPassword(ctx context.Context, arg UpdateControlPanelPasswordParams) error {
	_, err := q.db.Exec(ctx, updateControlPanelPassword, arg.PasswordHash, arg.ID)
	return err
}
