// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package sqlcgen

import (
	"context"
)

const dashboardCreateTenant = `-- name: DashboardCreateTenant :one
SELECT
    r.tenant_id::bigint AS tenant_id,
    r.project_id::bigint AS project_id,
    r.api_key_id::bigint AS api_key_id,
    r.membership_id::bigint AS membership_id
FROM dashboard_create_tenant(
    $1,
    $2,
    $3,
    $4,
    $5
) AS r(tenant_id, project_id, api_key_id, membership_id)
`

type DashboardCreateTenantParams struct {
	ActorUserID int64
	TenantName  string
	ProjectName string
	KeyHash     []byte
	KeyLabel    string
}

type DashboardCreateTenantRow struct {
	TenantID     int64
	ProjectID    int64
	ApiKeyID     int64
	MembershipID int64
}

func (q *Queries) DashboardCreateTenant(ctx context.Context, arg DashboardCreateTenantParams) (DashboardCreateTenantRow, error) {
	row := q.db.QueryRow(ctx, dashboardCreateTenant,
		arg.ActorUserID,
		arg.TenantName,
		arg.ProjectName,
		arg.KeyHash,
		arg.KeyLabel,
	)
	var i DashboardCreateTenantRow
	err := row.Scan(
		&i.TenantID,
		&i.ProjectID,
		&i.ApiKeyID,
		&i.MembershipID,
	)
	return i, err
}
