// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: end_users_verify.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEndUserForVerify = `-- name: GetEndUserForVerify :one
SELECT u.id,
       u.tenant_id,
       u.project_id,
       u.external_id,
       u.session_epoch,
       u.player_account_id,
       coalesce(u.email, '')::text AS email
FROM end_users u
JOIN tenants  t ON t.id = u.tenant_id  AND t.deleted_at IS NULL
JOIN projects p ON p.id = u.project_id AND p.deleted_at IS NULL
WHERE u.id = $1
  AND u.tenant_id = nullif(current_setting('app.tenant_id', true), '')::bigint
  AND u.deleted_at IS NULL
  AND u.disabled_at IS NULL
`

type GetEndUserForVerifyRow struct {
	ID              int64
	TenantID        int64
	ProjectID       int64
	ExternalID      string
	SessionEpoch    int32
	PlayerAccountID pgtype.UUID
	Email           string
}

// Lookup an end-user by ID for the POST /v1/end-users/verify endpoint
// (gameserver session-token verification). Filters deleted/disabled
// accounts so a forged token claiming a stale id rejects with 401.
// The explicit tenant_id predicate matches the project's RLS-via-GUC
// convention (Pool.Q sets app.tenant_id) and survives a hypothetical
// RLS disable; the JOINs against tenants/projects enforce the
// soft-delete kill-switch — a wound-down project can't continue to
// verify sessions.
func (q *Queries) GetEndUserForVerify(ctx context.Context, id int64) (GetEndUserForVerifyRow, error) {
	row := q.db.QueryRow(ctx, getEndUserForVerify, id)
	var i GetEndUserForVerifyRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.ExternalID,
		&i.SessionEpoch,
		&i.PlayerAccountID,
		&i.Email,
	)
	return i, err
}

const getEndUserSessionEpoch = `-- name: GetEndUserSessionEpoch :one
SELECT session_epoch FROM end_users WHERE id = $1
`

// PK lookup used at token issuance to snapshot the current epoch into the JWT.
func (q *Queries) GetEndUserSessionEpoch(ctx context.Context, id int64) (int32, error) {
	row := q.db.QueryRow(ctx, getEndUserSessionEpoch, id)
	var session_epoch int32
	err := row.Scan(&session_epoch)
	return session_epoch, err
}
