// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: friends.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteFriendEdge = `-- name: DeleteFriendEdge :exec
DELETE FROM friend_edges
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND from_user_id = $1
  AND to_user_id   = $2
`

type DeleteFriendEdgeParams struct {
	FromUserID int64
	ToUserID   int64
}

func (q *Queries) DeleteFriendEdge(ctx context.Context, arg DeleteFriendEdgeParams) error {
	_, err := q.db.Exec(ctx, deleteFriendEdge, arg.FromUserID, arg.ToUserID)
	return err
}

const getFriendEdge = `-- name: GetFriendEdge :one
SELECT id, status
FROM friend_edges
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND from_user_id = $1
  AND to_user_id   = $2
`

type GetFriendEdgeParams struct {
	FromUserID int64
	ToUserID   int64
}

type GetFriendEdgeRow struct {
	ID     int64
	Status string
}

func (q *Queries) GetFriendEdge(ctx context.Context, arg GetFriendEdgeParams) (GetFriendEdgeRow, error) {
	row := q.db.QueryRow(ctx, getFriendEdge, arg.FromUserID, arg.ToUserID)
	var i GetFriendEdgeRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const listFriendsByStatus = `-- name: ListFriendsByStatus :many
SELECT id, from_user_id, to_user_id, status, created_at, updated_at
FROM friend_edges
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND (from_user_id = $1 OR to_user_id = $1)
  AND status = $2
  AND id > $3
ORDER BY id ASC
LIMIT $4
`

type ListFriendsByStatusParams struct {
	FromUserID int64
	Status     string
	ID         int64
	Limit      int32
}

type ListFriendsByStatusRow struct {
	ID         int64
	FromUserID int64
	ToUserID   int64
	Status     string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) ListFriendsByStatus(ctx context.Context, arg ListFriendsByStatusParams) ([]ListFriendsByStatusRow, error) {
	rows, err := q.db.Query(ctx, listFriendsByStatus,
		arg.FromUserID,
		arg.Status,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFriendsByStatusRow
	for rows.Next() {
		var i ListFriendsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.FromUserID,
			&i.ToUserID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestFriend = `-- name: RequestFriend :one
INSERT INTO friend_edges (tenant_id, from_user_id, to_user_id, status)
VALUES (
    current_setting('app.tenant_id', true)::bigint,
    $1, $2, 'pending'
)
ON CONFLICT (tenant_id, from_user_id, to_user_id)
DO UPDATE SET status     = 'pending',
              updated_at = now()
WHERE friend_edges.status = 'rejected'
RETURNING id, status
`

type RequestFriendParams struct {
	FromUserID int64
	ToUserID   int64
}

type RequestFriendRow struct {
	ID     int64
	Status string
}

// The unique index keeps one current row per directed pair, so re-requests
// after rejection update in place. Pending/accepted are idempotent (the
// WHERE clause filters them out, leaving DO UPDATE a no-op). Blocked is
// terminal (the WHERE clause omits it). See migration 0012.
func (q *Queries) RequestFriend(ctx context.Context, arg RequestFriendParams) (RequestFriendRow, error) {
	row := q.db.QueryRow(ctx, requestFriend, arg.FromUserID, arg.ToUserID)
	var i RequestFriendRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const setFriendEdgeStatus = `-- name: SetFriendEdgeStatus :exec
UPDATE friend_edges
SET status     = $3,
    updated_at = now()
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND from_user_id = $1
  AND to_user_id   = $2
`

type SetFriendEdgeStatusParams struct {
	FromUserID int64
	ToUserID   int64
	Status     string
}

func (q *Queries) SetFriendEdgeStatus(ctx context.Context, arg SetFriendEdgeStatusParams) error {
	_, err := q.db.Exec(ctx, setFriendEdgeStatus, arg.FromUserID, arg.ToUserID, arg.Status)
	return err
}
