// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: friends.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const areFriendsAccepted = `-- name: AreFriendsAccepted :one
SELECT id FROM friend_edges
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND ((from_user_id = $1 AND to_user_id = $2)
       OR (from_user_id = $2 AND to_user_id = $1))
  AND status = 'accepted'
LIMIT 1
`

type AreFriendsAcceptedParams struct {
	FromUserID int64
	ToUserID   int64
}

// Returns the edge ID if an accepted friendship exists between the two
// users in either direction; pgx.ErrNoRows if they are not friends.
func (q *Queries) AreFriendsAccepted(ctx context.Context, arg AreFriendsAcceptedParams) (int64, error) {
	row := q.db.QueryRow(ctx, areFriendsAccepted, arg.FromUserID, arg.ToUserID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteFriendEdge = `-- name: DeleteFriendEdge :execrows
DELETE FROM friend_edges
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND ((from_user_id = $1 AND to_user_id = $2)
       OR (from_user_id = $2 AND to_user_id = $1))
`

type DeleteFriendEdgeParams struct {
	Me    int64
	Other int64
}

// Symmetric unfriend: the caller can be on either side of the edge. The
// previous one-directional query silently no-op'd when the friendship was
// inbound, so a "delete" returned 204 without actually removing anything.
func (q *Queries) DeleteFriendEdge(ctx context.Context, arg DeleteFriendEdgeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFriendEdge, arg.Me, arg.Other)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFriendEdge = `-- name: GetFriendEdge :one
SELECT id, status
FROM friend_edges
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND from_user_id = $1
  AND to_user_id   = $2
`

type GetFriendEdgeParams struct {
	FromUserID int64
	ToUserID   int64
}

type GetFriendEdgeRow struct {
	ID     int64
	Status string
}

func (q *Queries) GetFriendEdge(ctx context.Context, arg GetFriendEdgeParams) (GetFriendEdgeRow, error) {
	row := q.db.QueryRow(ctx, getFriendEdge, arg.FromUserID, arg.ToUserID)
	var i GetFriendEdgeRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const listAcceptedFriendIDs = `-- name: ListAcceptedFriendIDs :many
SELECT from_user_id, to_user_id
FROM friend_edges
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND (from_user_id = $1 OR to_user_id = $1)
  AND status = 'accepted'
`

type ListAcceptedFriendIDsRow struct {
	FromUserID int64
	ToUserID   int64
}

// Returns (from_user_id, to_user_id) pairs for all accepted friendships
// involving the given user. Callers resolve the "other" user by comparing
// each column against their own ID.
func (q *Queries) ListAcceptedFriendIDs(ctx context.Context, fromUserID int64) ([]ListAcceptedFriendIDsRow, error) {
	rows, err := q.db.Query(ctx, listAcceptedFriendIDs, fromUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAcceptedFriendIDsRow
	for rows.Next() {
		var i ListAcceptedFriendIDsRow
		if err := rows.Scan(&i.FromUserID, &i.ToUserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEndUserIdentitiesForUsers = `-- name: ListEndUserIdentitiesForUsers :many
SELECT id AS end_user_id, COALESCE(email::text, '')::text AS email, xuid
FROM end_users
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND id = ANY($1::bigint[])
`

type ListEndUserIdentitiesForUsersRow struct {
	EndUserID int64
	Email     string
	Xuid      *string
}

// Bulk-fetch email + xuid for a set of users, used to enrich friend lists.
// email is COALESCEd because anonymous users have none.
func (q *Queries) ListEndUserIdentitiesForUsers(ctx context.Context, endUserIds []int64) ([]ListEndUserIdentitiesForUsersRow, error) {
	rows, err := q.db.Query(ctx, listEndUserIdentitiesForUsers, endUserIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEndUserIdentitiesForUsersRow
	for rows.Next() {
		var i ListEndUserIdentitiesForUsersRow
		if err := rows.Scan(&i.EndUserID, &i.Email, &i.Xuid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFriendsByStatus = `-- name: ListFriendsByStatus :many
SELECT id, from_user_id, to_user_id, status, created_at, updated_at
FROM friend_edges
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND (from_user_id = $1 OR to_user_id = $1)
  AND status = $2
  AND id > $3
ORDER BY id ASC
LIMIT $4
`

type ListFriendsByStatusParams struct {
	FromUserID int64
	Status     string
	ID         int64
	Limit      int32
}

type ListFriendsByStatusRow struct {
	ID         int64
	FromUserID int64
	ToUserID   int64
	Status     string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) ListFriendsByStatus(ctx context.Context, arg ListFriendsByStatusParams) ([]ListFriendsByStatusRow, error) {
	rows, err := q.db.Query(ctx, listFriendsByStatus,
		arg.FromUserID,
		arg.Status,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFriendsByStatusRow
	for rows.Next() {
		var i ListFriendsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.FromUserID,
			&i.ToUserID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFriendsByStatusForCaller = `-- name: ListFriendsByStatusForCaller :many
SELECT id, from_user_id, to_user_id, status, created_at, updated_at
FROM friend_edges
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND (($1::text != 'blocked'
            AND (from_user_id = $2 OR to_user_id = $2))
       OR ($1::text = 'blocked'
            AND from_user_id = $2))
  AND status = $1
  AND id > $3
ORDER BY id ASC
LIMIT $4
`

type ListFriendsByStatusForCallerParams struct {
	Status   string
	Me       int64
	Cursor   int64
	RowLimit int32
}

type ListFriendsByStatusForCallerRow struct {
	ID         int64
	FromUserID int64
	ToUserID   int64
	Status     string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

// Caller-aware list. For 'blocked', only rows where the caller initiated
// the block are returned — never rows where the caller is the blockee
// (which would let a blocked user enumerate who blocked them).
func (q *Queries) ListFriendsByStatusForCaller(ctx context.Context, arg ListFriendsByStatusForCallerParams) ([]ListFriendsByStatusForCallerRow, error) {
	rows, err := q.db.Query(ctx, listFriendsByStatusForCaller,
		arg.Status,
		arg.Me,
		arg.Cursor,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFriendsByStatusForCallerRow
	for rows.Next() {
		var i ListFriendsByStatusForCallerRow
		if err := rows.Scan(
			&i.ID,
			&i.FromUserID,
			&i.ToUserID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestFriend = `-- name: RequestFriend :one
INSERT INTO friend_edges (tenant_id, from_user_id, to_user_id, status)
VALUES (
    current_setting('app.tenant_id', true)::bigint,
    $1, $2, 'pending'
)
ON CONFLICT (tenant_id, from_user_id, to_user_id)
DO UPDATE SET status     = 'pending',
              updated_at = now()
WHERE friend_edges.status = 'rejected'
RETURNING id, status
`

type RequestFriendParams struct {
	FromUserID int64
	ToUserID   int64
}

type RequestFriendRow struct {
	ID     int64
	Status string
}

// The unique index keeps one current row per directed pair, so re-requests
// after rejection update in place. Pending/accepted are idempotent (the
// WHERE clause filters them out, leaving DO UPDATE a no-op). Blocked is
// terminal (the WHERE clause omits it). See migration 0012.
func (q *Queries) RequestFriend(ctx context.Context, arg RequestFriendParams) (RequestFriendRow, error) {
	row := q.db.QueryRow(ctx, requestFriend, arg.FromUserID, arg.ToUserID)
	var i RequestFriendRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const setFriendEdgeStatus = `-- name: SetFriendEdgeStatus :exec
UPDATE friend_edges
SET status     = $3,
    updated_at = now()
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND from_user_id = $1
  AND to_user_id   = $2
`

type SetFriendEdgeStatusParams struct {
	FromUserID int64
	ToUserID   int64
	Status     string
}

func (q *Queries) SetFriendEdgeStatus(ctx context.Context, arg SetFriendEdgeStatusParams) error {
	_, err := q.db.Exec(ctx, setFriendEdgeStatus, arg.FromUserID, arg.ToUserID, arg.Status)
	return err
}
