// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: game_session_signal.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveSignalMembers = `-- name: CountActiveSignalMembers :one
SELECT count(DISTINCT p.player_id)
FROM game_session_peer p
JOIN game_session s ON s.id = p.session_id
WHERE s.id = $1
  AND s.project_id = $2
  AND s.state <> 'ended'
  AND s.expires_at > now()
  AND p.last_seen > now() - interval '30 seconds'
  AND p.player_id = ANY($3::bigint[])
`

type CountActiveSignalMembersParams struct {
	SessionID string
	ProjectID int64
	PlayerIds []int64
}

// Counts how many of the given players are ACTIVE members (last_seen within
// 30 s, matching ListGameSessionPeers/CountActiveGameSessionPeers) of an
// open, unexpired session in this project. The signal handlers pass both
// endpoints for a send (expecting 2) or just the caller for a poll
// (expecting 1), so the count defines "both peers are in the same live
// session" without diverging from the roster the clients themselves see.
func (q *Queries) CountActiveSignalMembers(ctx context.Context, arg CountActiveSignalMembersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSignalMembers, arg.SessionID, arg.ProjectID, arg.PlayerIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentGameSessionSignals = `-- name: CountRecentGameSessionSignals :one
SELECT count(*) FROM game_session_signal
WHERE session_id = $1
  AND from_player_id = $2
  AND created_at > now() - interval '1 minute'
`

type CountRecentGameSessionSignalsParams struct {
	SessionID    string
	FromPlayerID int64
}

// Signals this player has sent into this session in the trailing minute; the
// handler rejects once it reaches the per-minute cap.
func (q *Queries) CountRecentGameSessionSignals(ctx context.Context, arg CountRecentGameSessionSignalsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentGameSessionSignals, arg.SessionID, arg.FromPlayerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExpiredGameSessionSignalsForTenant = `-- name: DeleteExpiredGameSessionSignalsForTenant :execrows
DELETE FROM game_session_signal
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND expires_at < now()
`

// Removes signals past their two-minute expiry for the current tenant. Called
// per tenant by the game-session GC sweep so long-lived sessions don't
// accumulate expired rows (session/tenant deletion already cascades the rest).
func (q *Queries) DeleteExpiredGameSessionSignalsForTenant(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredGameSessionSignalsForTenant)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertGameSessionSignal = `-- name: InsertGameSessionSignal :one
INSERT INTO game_session_signal
    (tenant_id, session_id, from_player_id, to_player_id, negotiation_id, kind, payload)
VALUES (
    current_setting('app.tenant_id', true)::bigint,
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id
`

type InsertGameSessionSignalParams struct {
	SessionID     string
	FromPlayerID  int64
	ToPlayerID    int64
	NegotiationID string
	Kind          string
	Payload       string
}

func (q *Queries) InsertGameSessionSignal(ctx context.Context, arg InsertGameSessionSignalParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertGameSessionSignal,
		arg.SessionID,
		arg.FromPlayerID,
		arg.ToPlayerID,
		arg.NegotiationID,
		arg.Kind,
		arg.Payload,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listGameSessionSignalsForRecipient = `-- name: ListGameSessionSignalsForRecipient :many
SELECT id, from_player_id, to_player_id, negotiation_id, kind, payload, created_at
FROM game_session_signal
WHERE session_id = $1
  AND to_player_id = $2
  AND id > $3
  AND expires_at > now()
ORDER BY id ASC
LIMIT 64
`

type ListGameSessionSignalsForRecipientParams struct {
	SessionID  string
	ToPlayerID int64
	AfterID    int64
}

type ListGameSessionSignalsForRecipientRow struct {
	ID            int64
	FromPlayerID  int64
	ToPlayerID    int64
	NegotiationID string
	Kind          string
	Payload       string
	CreatedAt     pgtype.Timestamptz
}

// Recipient-scoped, cursor-ordered, unexpired signals. The to_player_id filter
// plus RLS ensure a player only ever reads signals addressed to them, and the
// id > after_id cursor makes repeat polls return only new signals.
func (q *Queries) ListGameSessionSignalsForRecipient(ctx context.Context, arg ListGameSessionSignalsForRecipientParams) ([]ListGameSessionSignalsForRecipientRow, error) {
	rows, err := q.db.Query(ctx, listGameSessionSignalsForRecipient, arg.SessionID, arg.ToPlayerID, arg.AfterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGameSessionSignalsForRecipientRow
	for rows.Next() {
		var i ListGameSessionSignalsForRecipientRow
		if err := rows.Scan(
			&i.ID,
			&i.FromPlayerID,
			&i.ToPlayerID,
			&i.NegotiationID,
			&i.Kind,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSignalRate = `-- name: LockSignalRate :exec
SELECT pg_advisory_xact_lock(hashtextextended('game_session_signal_rate', $1))
`

// Serializes a player's concurrent signal sends within the transaction so the
// per-minute count+insert below can't be raced past the cap under READ
// COMMITTED. player_id (project_players.id) is globally unique, so the lock
// key never collides across tenants. Released on commit/rollback.
func (q *Queries) LockSignalRate(ctx context.Context, fromPlayerID int64) error {
	_, err := q.db.Exec(ctx, lockSignalRate, fromPlayerID)
	return err
}
