// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: game_invite.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGameInvite = `-- name: CreateGameInvite :one
INSERT INTO game_invite (tenant_id, project_id, from_user_id, to_user_id, session_id, join_code, expires_at)
VALUES (
    current_setting('app.tenant_id', true)::bigint,
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id
`

type CreateGameInviteParams struct {
	ProjectID  int64
	FromUserID int64
	ToUserID   int64
	SessionID  string
	JoinCode   string
	ExpiresAt  pgtype.Timestamptz
}

func (q *Queries) CreateGameInvite(ctx context.Context, arg CreateGameInviteParams) (int64, error) {
	row := q.db.QueryRow(ctx, createGameInvite,
		arg.ProjectID,
		arg.FromUserID,
		arg.ToUserID,
		arg.SessionID,
		arg.JoinCode,
		arg.ExpiresAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteExpiredGameInvitesForTenant = `-- name: DeleteExpiredGameInvitesForTenant :execrows
DELETE FROM game_invite
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND expires_at < now()
`

// Removes invites past their expiry for the current tenant. Called per
// tenant by the GC goroutine.
func (q *Queries) DeleteExpiredGameInvitesForTenant(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredGameInvitesForTenant)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGameInvite = `-- name: DeleteGameInvite :execrows
DELETE FROM game_invite
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND id        = $1
  AND (from_user_id = $2 OR to_user_id = $2)
`

type DeleteGameInviteParams struct {
	ID       int64
	CallerID int64
}

// Either sender (cancel) or recipient (decline/dismiss) may delete an invite.
func (q *Queries) DeleteGameInvite(ctx context.Context, arg DeleteGameInviteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGameInvite, arg.ID, arg.CallerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEndUserIDByEmail = `-- name: GetEndUserIDByEmail :one
SELECT id FROM end_users
WHERE tenant_id  = current_setting('app.tenant_id', true)::bigint
  AND project_id = $1
  AND email      = $2
  AND deleted_at IS NULL
`

type GetEndUserIDByEmailParams struct {
	ProjectID int64
	Email     *string
}

// Resolves an invite recipient by email within the caller's project.
func (q *Queries) GetEndUserIDByEmail(ctx context.Context, arg GetEndUserIDByEmailParams) (int64, error) {
	row := q.db.QueryRow(ctx, getEndUserIDByEmail, arg.ProjectID, arg.Email)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listPendingGameInvites = `-- name: ListPendingGameInvites :many
SELECT
    gi.id,
    gi.from_user_id,
    gi.session_id,
    gi.join_code,
    gi.expires_at,
    COALESCE(u.email::text, '')::text AS from_email,
    u.xuid                            AS from_xuid
FROM game_invite gi
LEFT JOIN end_users u ON u.id = gi.from_user_id
WHERE gi.tenant_id   = current_setting('app.tenant_id', true)::bigint
  AND gi.to_user_id  = $1
  AND gi.expires_at  > now()
ORDER BY gi.id ASC
`

type ListPendingGameInvitesRow struct {
	ID         int64
	FromUserID int64
	SessionID  string
	JoinCode   string
	ExpiresAt  pgtype.Timestamptz
	FromEmail  string
	FromXuid   *string
}

// Returns unexpired invites for the target user, enriched with the sender's
// email and optional xuid for display.
func (q *Queries) ListPendingGameInvites(ctx context.Context, toUserID int64) ([]ListPendingGameInvitesRow, error) {
	rows, err := q.db.Query(ctx, listPendingGameInvites, toUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingGameInvitesRow
	for rows.Next() {
		var i ListPendingGameInvitesRow
		if err := rows.Scan(
			&i.ID,
			&i.FromUserID,
			&i.SessionID,
			&i.JoinCode,
			&i.ExpiresAt,
			&i.FromEmail,
			&i.FromXuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
