// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leaderboards.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEntries = `-- name: CountEntries :one
SELECT COUNT(*)::bigint
FROM leaderboard_entries
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND leaderboard_id = $1
`

func (q *Queries) CountEntries(ctx context.Context, leaderboardID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countEntries, leaderboardID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createLeaderboard = `-- name: CreateLeaderboard :one
INSERT INTO leaderboards (tenant_id, project_id, name, sort_order)
VALUES (
    current_setting('app.tenant_id', true)::bigint,
    $1, $2, $3
)
RETURNING id
`

type CreateLeaderboardParams struct {
	ProjectID int64
	Name      string
	SortOrder string
}

func (q *Queries) CreateLeaderboard(ctx context.Context, arg CreateLeaderboardParams) (int64, error) {
	row := q.db.QueryRow(ctx, createLeaderboard, arg.ProjectID, arg.Name, arg.SortOrder)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getLeaderboard = `-- name: GetLeaderboard :one
SELECT id, sort_order
FROM leaderboards
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND id = $1
  AND deleted_at IS NULL
`

type GetLeaderboardRow struct {
	ID        int64
	SortOrder string
}

func (q *Queries) GetLeaderboard(ctx context.Context, id int64) (GetLeaderboardRow, error) {
	row := q.db.QueryRow(ctx, getLeaderboard, id)
	var i GetLeaderboardRow
	err := row.Scan(&i.ID, &i.SortOrder)
	return i, err
}

const leaderboardRangeByRank = `-- name: LeaderboardRangeByRank :many
WITH ranked AS (
    SELECT end_user_id,
           MAX(score)::bigint AS best_score,
           RANK() OVER (ORDER BY MAX(score) DESC, end_user_id ASC) AS r
    FROM leaderboard_entries
    WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
      AND leaderboard_id = $1
    GROUP BY end_user_id
)
SELECT end_user_id, best_score, r::bigint AS rank
FROM ranked
WHERE r BETWEEN $2::bigint AND $3::bigint
ORDER BY r
`

type LeaderboardRangeByRankParams struct {
	LeaderboardID int64
	RankLow       int64
	RankHigh      int64
}

type LeaderboardRangeByRankRow struct {
	EndUserID int64
	BestScore int64
	Rank      int64
}

func (q *Queries) LeaderboardRangeByRank(ctx context.Context, arg LeaderboardRangeByRankParams) ([]LeaderboardRangeByRankRow, error) {
	rows, err := q.db.Query(ctx, leaderboardRangeByRank, arg.LeaderboardID, arg.RankLow, arg.RankHigh)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaderboardRangeByRankRow
	for rows.Next() {
		var i LeaderboardRangeByRankRow
		if err := rows.Scan(&i.EndUserID, &i.BestScore, &i.Rank); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const leaderboardUserRank = `-- name: LeaderboardUserRank :one
WITH ranked AS (
    SELECT end_user_id,
           RANK() OVER (ORDER BY MAX(score) DESC, end_user_id ASC) AS r
    FROM leaderboard_entries
    WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
      AND leaderboard_id = $1
    GROUP BY end_user_id
)
SELECT r::bigint AS rank
FROM ranked
WHERE end_user_id = $2
`

type LeaderboardUserRankParams struct {
	LeaderboardID int64
	EndUserID     int64
}

func (q *Queries) LeaderboardUserRank(ctx context.Context, arg LeaderboardUserRankParams) (int64, error) {
	row := q.db.QueryRow(ctx, leaderboardUserRank, arg.LeaderboardID, arg.EndUserID)
	var rank int64
	err := row.Scan(&rank)
	return rank, err
}

const submitScore = `-- name: SubmitScore :one
INSERT INTO leaderboard_entries (
    tenant_id, leaderboard_id, end_user_id, score, recorded_at
)
VALUES (
    current_setting('app.tenant_id', true)::bigint,
    $1, $2, $3, now()
)
RETURNING id, recorded_at
`

type SubmitScoreParams struct {
	LeaderboardID int64
	EndUserID     int64
	Score         int64
}

type SubmitScoreRow struct {
	ID         int64
	RecordedAt pgtype.Timestamptz
}

func (q *Queries) SubmitScore(ctx context.Context, arg SubmitScoreParams) (SubmitScoreRow, error) {
	row := q.db.QueryRow(ctx, submitScore, arg.LeaderboardID, arg.EndUserID, arg.Score)
	var i SubmitScoreRow
	err := row.Scan(&i.ID, &i.RecordedAt)
	return i, err
}

const topN = `-- name: TopN :many
SELECT le.end_user_id,
       MAX(le.score)::bigint AS best_score,
       MIN(le.recorded_at)::timestamptz AS first_seen
FROM leaderboard_entries le
WHERE le.tenant_id = current_setting('app.tenant_id', true)::bigint
  AND le.leaderboard_id = $1
GROUP BY le.end_user_id
ORDER BY best_score DESC
LIMIT $2
`

type TopNParams struct {
	LeaderboardID int64
	Limit         int32
}

type TopNRow struct {
	EndUserID int64
	BestScore int64
	FirstSeen pgtype.Timestamptz
}

func (q *Queries) TopN(ctx context.Context, arg TopNParams) ([]TopNRow, error) {
	rows, err := q.db.Query(ctx, topN, arg.LeaderboardID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopNRow
	for rows.Next() {
		var i TopNRow
		if err := rows.Scan(&i.EndUserID, &i.BestScore, &i.FirstSeen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
