// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matchmaker.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelMatchmakingTicket = `-- name: CancelMatchmakingTicket :one
UPDATE matchmaking_tickets
SET status = 'cancelled'
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND id = $1
  AND status = 'queued'
RETURNING id
`

func (q *Queries) CancelMatchmakingTicket(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, cancelMatchmakingTicket, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const getMatchmakingTicket = `-- name: GetMatchmakingTicket :one
SELECT id, tenant_id, project_id, end_user_id, region, game_mode,
       attributes, status::text AS status, match_address,
       created_at, matched_at
FROM matchmaking_tickets
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND id = $1
`

type GetMatchmakingTicketRow struct {
	ID           int64
	TenantID     int64
	ProjectID    int64
	EndUserID    int64
	Region       string
	GameMode     string
	Attributes   []byte
	Status       string
	MatchAddress string
	CreatedAt    pgtype.Timestamptz
	MatchedAt    pgtype.Timestamptz
}

func (q *Queries) GetMatchmakingTicket(ctx context.Context, id int64) (GetMatchmakingTicketRow, error) {
	row := q.db.QueryRow(ctx, getMatchmakingTicket, id)
	var i GetMatchmakingTicketRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.EndUserID,
		&i.Region,
		&i.GameMode,
		&i.Attributes,
		&i.Status,
		&i.MatchAddress,
		&i.CreatedAt,
		&i.MatchedAt,
	)
	return i, err
}

const insertMatchmakingTicket = `-- name: InsertMatchmakingTicket :one
INSERT INTO matchmaking_tickets (
    tenant_id, project_id, end_user_id, region, game_mode, attributes
)
VALUES (
    current_setting('app.tenant_id', true)::bigint,
    $1, $2, $3, $4, $5
)
RETURNING id, status::text AS status, created_at
`

type InsertMatchmakingTicketParams struct {
	ProjectID  int64
	EndUserID  int64
	Region     string
	GameMode   string
	Attributes []byte
}

type InsertMatchmakingTicketRow struct {
	ID        int64
	Status    string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertMatchmakingTicket(ctx context.Context, arg InsertMatchmakingTicketParams) (InsertMatchmakingTicketRow, error) {
	row := q.db.QueryRow(ctx, insertMatchmakingTicket,
		arg.ProjectID,
		arg.EndUserID,
		arg.Region,
		arg.GameMode,
		arg.Attributes,
	)
	var i InsertMatchmakingTicketRow
	err := row.Scan(&i.ID, &i.Status, &i.CreatedAt)
	return i, err
}

const listMatchmakerBucketsForProject = `-- name: ListMatchmakerBucketsForProject :many
SELECT region,
       game_mode,
       status::text AS status,
       count(*)::bigint AS ticket_count,
       min(created_at)::timestamptz AS oldest
FROM matchmaking_tickets
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND project_id = $1
GROUP BY region, game_mode, status
ORDER BY region, game_mode, status
`

type ListMatchmakerBucketsForProjectRow struct {
	Region      string
	GameMode    string
	Status      string
	TicketCount int64
	Oldest      pgtype.Timestamptz
}

// Dashboard matchmaker page: queue depth per (region, game_mode) bucket for
// the current tenant's project, plus oldest queued ticket so operators can
// spot stuck buckets at a glance.
func (q *Queries) ListMatchmakerBucketsForProject(ctx context.Context, projectID int64) ([]ListMatchmakerBucketsForProjectRow, error) {
	rows, err := q.db.Query(ctx, listMatchmakerBucketsForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchmakerBucketsForProjectRow
	for rows.Next() {
		var i ListMatchmakerBucketsForProjectRow
		if err := rows.Scan(
			&i.Region,
			&i.GameMode,
			&i.Status,
			&i.TicketCount,
			&i.Oldest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadyMatchmakerBuckets = `-- name: ListReadyMatchmakerBuckets :many
SELECT tenant_id, project_id, region, game_mode, count(*) AS ticket_count
FROM matchmaking_tickets
WHERE status = 'queued'
GROUP BY tenant_id, project_id, region, game_mode
HAVING count(*) >= $1::int
ORDER BY tenant_id, project_id, region, game_mode
`

type ListReadyMatchmakerBucketsRow struct {
	TenantID    int64
	ProjectID   int64
	Region      string
	GameMode    string
	TicketCount int64
}

func (q *Queries) ListReadyMatchmakerBuckets(ctx context.Context, dollar_1 int32) ([]ListReadyMatchmakerBucketsRow, error) {
	rows, err := q.db.Query(ctx, listReadyMatchmakerBuckets, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReadyMatchmakerBucketsRow
	for rows.Next() {
		var i ListReadyMatchmakerBucketsRow
		if err := rows.Scan(
			&i.TenantID,
			&i.ProjectID,
			&i.Region,
			&i.GameMode,
			&i.TicketCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMatchmakerFailed = `-- name: MarkMatchmakerFailed :exec
UPDATE matchmaking_tickets
SET status = 'failed'
WHERE id = ANY($1::bigint[])
`

func (q *Queries) MarkMatchmakerFailed(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.Exec(ctx, markMatchmakerFailed, dollar_1)
	return err
}

const markMatchmakerMatched = `-- name: MarkMatchmakerMatched :exec
UPDATE matchmaking_tickets
SET match_address = $2,
    matched_at    = now()
WHERE id = ANY($1::bigint[])
`

type MarkMatchmakerMatchedParams struct {
	Column1      []int64
	MatchAddress string
}

func (q *Queries) MarkMatchmakerMatched(ctx context.Context, arg MarkMatchmakerMatchedParams) error {
	_, err := q.db.Exec(ctx, markMatchmakerMatched, arg.Column1, arg.MatchAddress)
	return err
}

const popMatchmakerBucket = `-- name: PopMatchmakerBucket :many
WITH candidates AS (
    SELECT mt.id
    FROM matchmaking_tickets mt
    WHERE mt.status = 'queued'
      AND mt.tenant_id = $1
      AND mt.project_id = $2
      AND mt.region = $3
      AND mt.game_mode = $4
    ORDER BY mt.created_at, mt.id
    LIMIT $5::int
    FOR UPDATE SKIP LOCKED
)
UPDATE matchmaking_tickets t
SET status = 'matched'
FROM candidates c
WHERE t.id = c.id
RETURNING t.id, t.tenant_id, t.project_id, t.end_user_id, t.region,
          t.game_mode, t.attributes, t.status::text AS status,
          t.match_address, t.created_at, t.matched_at
`

type PopMatchmakerBucketParams struct {
	TenantID  int64
	ProjectID int64
	Region    string
	GameMode  string
	Column5   int32
}

type PopMatchmakerBucketRow struct {
	ID           int64
	TenantID     int64
	ProjectID    int64
	EndUserID    int64
	Region       string
	GameMode     string
	Attributes   []byte
	Status       string
	MatchAddress string
	CreatedAt    pgtype.Timestamptz
	MatchedAt    pgtype.Timestamptz
}

func (q *Queries) PopMatchmakerBucket(ctx context.Context, arg PopMatchmakerBucketParams) ([]PopMatchmakerBucketRow, error) {
	rows, err := q.db.Query(ctx, popMatchmakerBucket,
		arg.TenantID,
		arg.ProjectID,
		arg.Region,
		arg.GameMode,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PopMatchmakerBucketRow
	for rows.Next() {
		var i PopMatchmakerBucketRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.EndUserID,
			&i.Region,
			&i.GameMode,
			&i.Attributes,
			&i.Status,
			&i.MatchAddress,
			&i.CreatedAt,
			&i.MatchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
