// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp_tokens.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveMCPTokens = `-- name: CountActiveMCPTokens :one
SELECT count(*)::bigint
FROM mcp_tokens
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND project_id = $1
  AND revoked_at IS NULL
  AND expires_at > now()
`

func (q *Queries) CountActiveMCPTokens(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveMCPTokens, projectID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createMCPToken = `-- name: CreateMCPToken :one
INSERT INTO mcp_tokens (
    tenant_id, project_id, created_by_user_id, label, token_hash, token_hint,
    scopes, expires_at
)
VALUES (
    current_setting('app.tenant_id', true)::bigint,
    $1, $2, $3,
    $4, $5, $6::text[],
    $7
)
RETURNING id
`

type CreateMCPTokenParams struct {
	ProjectID       int64
	CreatedByUserID int64
	Label           string
	TokenHash       []byte
	TokenHint       string
	Scopes          []string
	ExpiresAt       pgtype.Timestamptz
}

func (q *Queries) CreateMCPToken(ctx context.Context, arg CreateMCPTokenParams) (int64, error) {
	row := q.db.QueryRow(ctx, createMCPToken,
		arg.ProjectID,
		arg.CreatedByUserID,
		arg.Label,
		arg.TokenHash,
		arg.TokenHint,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getMCPTokenByHash = `-- name: GetMCPTokenByHash :one
SELECT k.id, k.tenant_id, k.project_id, k.created_by_user_id, k.scopes,
       k.expires_at, k.revoked_at, k.last_used_at,
       (t.disabled_at IS NOT NULL OR t.deleted_at IS NOT NULL)::bool AS tenant_disabled,
       (u.disabled_at IS NOT NULL)::bool AS creator_disabled
FROM mcp_tokens k
JOIN tenants t ON t.id = k.tenant_id
JOIN control_panel_users u ON u.id = k.created_by_user_id
WHERE k.token_hash = $1
`

type GetMCPTokenByHashRow struct {
	ID              int64
	TenantID        int64
	ProjectID       int64
	CreatedByUserID int64
	Scopes          []string
	ExpiresAt       pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
	LastUsedAt      pgtype.Timestamptz
	TenantDisabled  bool
	CreatorDisabled bool
}

// Runs with no tenant set (mcp_tokens_bootstrap and tenants_bootstrap allow
// it). projects has no bootstrap policy, so the project check is a second
// query in the tenant scope.
func (q *Queries) GetMCPTokenByHash(ctx context.Context, tokenHash []byte) (GetMCPTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getMCPTokenByHash, tokenHash)
	var i GetMCPTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.CreatedByUserID,
		&i.Scopes,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.TenantDisabled,
		&i.CreatorDisabled,
	)
	return i, err
}

const getMCPTokenCreator = `-- name: GetMCPTokenCreator :one
SELECT created_by_user_id
FROM mcp_tokens
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND project_id = $1
  AND id = $2
  AND revoked_at IS NULL
`

type GetMCPTokenCreatorParams struct {
	ProjectID int64
	ID        int64
}

func (q *Queries) GetMCPTokenCreator(ctx context.Context, arg GetMCPTokenCreatorParams) (int64, error) {
	row := q.db.QueryRow(ctx, getMCPTokenCreator, arg.ProjectID, arg.ID)
	var created_by_user_id int64
	err := row.Scan(&created_by_user_id)
	return created_by_user_id, err
}

const listMCPTokensForProject = `-- name: ListMCPTokensForProject :many
SELECT k.id, k.label, k.token_hint, k.scopes, k.created_by_user_id,
       u.email AS creator_email, k.expires_at, k.last_used_at, k.created_at
FROM mcp_tokens k
JOIN control_panel_users u ON u.id = k.created_by_user_id
WHERE k.tenant_id = current_setting('app.tenant_id', true)::bigint
  AND k.project_id = $1
  AND k.revoked_at IS NULL
ORDER BY k.id DESC
LIMIT 100
`

type ListMCPTokensForProjectRow struct {
	ID              int64
	Label           string
	TokenHint       string
	Scopes          []string
	CreatedByUserID int64
	CreatorEmail    string
	ExpiresAt       pgtype.Timestamptz
	LastUsedAt      pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) ListMCPTokensForProject(ctx context.Context, projectID int64) ([]ListMCPTokensForProjectRow, error) {
	rows, err := q.db.Query(ctx, listMCPTokensForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMCPTokensForProjectRow
	for rows.Next() {
		var i ListMCPTokensForProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.TokenHint,
			&i.Scopes,
			&i.CreatedByUserID,
			&i.CreatorEmail,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProjectForMCPTokenCreate = `-- name: LockProjectForMCPTokenCreate :one
SELECT id FROM projects
WHERE id = $1
  AND tenant_id = current_setting('app.tenant_id', true)::bigint
  AND deleted_at IS NULL
FOR UPDATE
`

func (q *Queries) LockProjectForMCPTokenCreate(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockProjectForMCPTokenCreate, projectID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const projectIsLive = `-- name: ProjectIsLive :one
SELECT EXISTS (
    SELECT 1 FROM projects
    WHERE id = $1
      AND tenant_id = current_setting('app.tenant_id', true)::bigint
      AND deleted_at IS NULL
)::bool
`

func (q *Queries) ProjectIsLive(ctx context.Context, projectID int64) (bool, error) {
	row := q.db.QueryRow(ctx, projectIsLive, projectID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const revokeMCPToken = `-- name: RevokeMCPToken :execrows
UPDATE mcp_tokens
SET revoked_at = now()
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND project_id = $1
  AND id = $2
  AND revoked_at IS NULL
`

type RevokeMCPTokenParams struct {
	ProjectID int64
	ID        int64
}

func (q *Queries) RevokeMCPToken(ctx context.Context, arg RevokeMCPTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeMCPToken, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchMCPTokenLastUsed = `-- name: TouchMCPTokenLastUsed :exec
UPDATE mcp_tokens
SET last_used_at = now()
WHERE id = $1
  AND tenant_id = current_setting('app.tenant_id', true)::bigint
  AND (last_used_at IS NULL OR last_used_at < now() - interval '1 minute')
`

// At most one write per minute for each token.
func (q *Queries) TouchMCPTokenLastUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchMCPTokenLastUsed, id)
	return err
}
