// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type APIKey struct {
	ID        int64
	TenantID  int64
	ProjectID *int64
	KeyHash   []byte
	Label     *string
	Scopes    []string
	CreatedAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

type AuditLog struct {
	ID          int64
	TenantID    int64
	ActorUserID *int64
	Action      string
	Target      *string
	Payload     []byte
	OccurredAt  pgtype.Timestamptz
}

type EndUser struct {
	ID                         int64
	TenantID                   int64
	ProjectID                  int64
	ExternalID                 string
	Email                      *string
	EmailVerifiedAt            pgtype.Timestamptz
	PasswordHash               []byte
	CreatedAt                  pgtype.Timestamptz
	DeletedAt                  pgtype.Timestamptz
	EmailVerificationHash      []byte
	EmailVerificationExpiresAt pgtype.Timestamptz
}

// One directed edge per (tenant, from, to). Status transitions are managed via UPSERT in the handler: a re-request after rejection updates status pending; pending/accepted are idempotent; blocked is terminal. See migration 0012 for the contract.
type FriendEdge struct {
	ID         int64
	TenantID   int64
	FromUserID int64
	ToUserID   int64
	Status     string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Leaderboard struct {
	ID        int64
	TenantID  int64
	ProjectID int64
	Name      string
	SortOrder string
	CreatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type LeaderboardEntry struct {
	ID            int64
	TenantID      int64
	LeaderboardID int64
	EndUserID     int64
	Score         int64
	RecordedAt    pgtype.Timestamptz
}

type Project struct {
	ID        int64
	TenantID  int64
	Name      string
	CreatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type Session struct {
	ID          int64
	TenantID    int64
	EndUserID   int64
	RefreshHash []byte
	ExpiresAt   pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type StorageObject struct {
	ID          int64
	TenantID    int64
	ProjectID   int64
	OwnerUserID int64
	Key         string
	Value       []byte
	Version     int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type Tenant struct {
	ID                int64
	Name              string
	Tier              string
	CreatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	CustomTokenSecret []byte
}

type UsageSample struct {
	ID          int64
	TenantID    int64
	ProjectID   int64
	Ts          pgtype.Timestamptz
	Ccu         int32
	Requests    int64
	BytesEgress int64
}
