// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: player_bans.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpAccountPlayerEpochsInTenant = `-- name: BumpAccountPlayerEpochsInTenant :exec
UPDATE project_players
SET session_epoch = session_epoch + 1
WHERE tenant_id = $1
  AND player_account_id = $2
`

type BumpAccountPlayerEpochsInTenantParams struct {
	TenantID        int64
	PlayerAccountID pgtype.UUID
}

// Bump every player of an account within a tenant (tenant-ban path), so all
// their live JWTs are rejected at server-verify immediately.
func (q *Queries) BumpAccountPlayerEpochsInTenant(ctx context.Context, arg BumpAccountPlayerEpochsInTenantParams) error {
	_, err := q.db.Exec(ctx, bumpAccountPlayerEpochsInTenant, arg.TenantID, arg.PlayerAccountID)
	return err
}

const bumpPlayerSessionEpoch = `-- name: BumpPlayerSessionEpoch :exec
UPDATE project_players
SET session_epoch = session_epoch + 1
WHERE id = $1
`

// Single player (project disable path).
func (q *Queries) BumpPlayerSessionEpoch(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, bumpPlayerSessionEpoch, id)
	return err
}

const createTenantPlayerBan = `-- name: CreateTenantPlayerBan :exec

INSERT INTO tenant_player_bans (tenant_id, player_account_id, reason, created_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, player_account_id)
DO UPDATE SET reason = $3, created_by = $4, created_at = now()
`

type CreateTenantPlayerBanParams struct {
	TenantID        int64
	PlayerAccountID pgtype.UUID
	Reason          *string
	CreatedBy       *int64
}

// Tenant-wide player bans. tenant_player_bans has no RLS, so every query
// filters tenant_id explicitly. Enforcement runs in both tenant Pool.Q and
// account BootstrapQ contexts.
func (q *Queries) CreateTenantPlayerBan(ctx context.Context, arg CreateTenantPlayerBanParams) error {
	_, err := q.db.Exec(ctx, createTenantPlayerBan,
		arg.TenantID,
		arg.PlayerAccountID,
		arg.Reason,
		arg.CreatedBy,
	)
	return err
}

const deleteTenantPlayerBan = `-- name: DeleteTenantPlayerBan :execrows
DELETE FROM tenant_player_bans
WHERE tenant_id = $1
  AND player_account_id = $2
`

type DeleteTenantPlayerBanParams struct {
	TenantID        int64
	PlayerAccountID pgtype.UUID
}

func (q *Queries) DeleteTenantPlayerBan(ctx context.Context, arg DeleteTenantPlayerBanParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTenantPlayerBan, arg.TenantID, arg.PlayerAccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const isAccountBannedInTenant = `-- name: IsAccountBannedInTenant :one
SELECT id FROM tenant_player_bans
WHERE tenant_id = $1
  AND player_account_id = $2
LIMIT 1
`

type IsAccountBannedInTenantParams struct {
	TenantID        int64
	PlayerAccountID pgtype.UUID
}

func (q *Queries) IsAccountBannedInTenant(ctx context.Context, arg IsAccountBannedInTenantParams) (int64, error) {
	row := q.db.QueryRow(ctx, isAccountBannedInTenant, arg.TenantID, arg.PlayerAccountID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const isPlayerBannedByTenant = `-- name: IsPlayerBannedByTenant :one
SELECT b.id
FROM project_players u
JOIN tenant_player_bans b
  ON b.player_account_id = u.player_account_id
 AND b.tenant_id = u.tenant_id
WHERE u.id = $1
  AND u.deleted_at IS NULL
LIMIT 1
`

// Enforcement helper: is the given player's linked account tenant-banned in
// the player's own tenant? Runs in a tenant Pool.Q (project_players RLS-filtered).
// Returns pgx.ErrNoRows when not banned (or the player is unlinked).
func (q *Queries) IsPlayerBannedByTenant(ctx context.Context, playerID int64) (int64, error) {
	row := q.db.QueryRow(ctx, isPlayerBannedByTenant, playerID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listTenantPlayerBans = `-- name: ListTenantPlayerBans :many
SELECT b.player_account_id, a.email::text AS email, b.reason, b.created_at
FROM tenant_player_bans b
JOIN player_accounts a ON a.id = b.player_account_id
WHERE b.tenant_id = $1
ORDER BY b.created_at DESC
`

type ListTenantPlayerBansRow struct {
	PlayerAccountID pgtype.UUID
	Email           string
	Reason          *string
	CreatedAt       pgtype.Timestamptz
}

// Dashboard list for a tenant, enriched with the banned account's email.
func (q *Queries) ListTenantPlayerBans(ctx context.Context, tenantID int64) ([]ListTenantPlayerBansRow, error) {
	rows, err := q.db.Query(ctx, listTenantPlayerBans, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTenantPlayerBansRow
	for rows.Next() {
		var i ListTenantPlayerBansRow
		if err := rows.Scan(
			&i.PlayerAccountID,
			&i.Email,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
