// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: relay_usage.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRelaySessionUsage = `-- name: GetRelaySessionUsage :one
SELECT sessions
FROM relay_session_usage
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND month = $1
`

func (q *Queries) GetRelaySessionUsage(ctx context.Context, month pgtype.Date) (int64, error) {
	row := q.db.QueryRow(ctx, getRelaySessionUsage, month)
	var sessions int64
	err := row.Scan(&sessions)
	return sessions, err
}

const incrementRelaySessions = `-- name: IncrementRelaySessions :one
INSERT INTO relay_session_usage (tenant_id, month, sessions)
VALUES (current_setting('app.tenant_id', true)::bigint, $1, 1)
ON CONFLICT (tenant_id, month) DO UPDATE
SET sessions = relay_session_usage.sessions + 1,
    updated_at = now()
WHERE $2::bigint < 0
   OR relay_session_usage.sessions < $2::bigint
RETURNING sessions
`

type IncrementRelaySessionsParams struct {
	Month     pgtype.Date
	Allowance int64
}

// Counts one managed-relay credential issuance for the tenant month. The
// allowance check and the increment are one atomic statement: past the
// allowance the conflict-update WHERE fails and no row returns (refuse new
// issuance). A negative allowance means unmetered. Runs in tenant RLS context.
func (q *Queries) IncrementRelaySessions(ctx context.Context, arg IncrementRelaySessionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, incrementRelaySessions, arg.Month, arg.Allowance)
	var sessions int64
	err := row.Scan(&sessions)
	return sessions, err
}

const markRelayUsageWarned100 = `-- name: MarkRelayUsageWarned100 :execrows
UPDATE relay_session_usage
SET warned_100_at = now(), updated_at = now()
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND month = $1
  AND warned_100_at IS NULL
`

// Claims the right to send the single 100% warning email for this month.
func (q *Queries) MarkRelayUsageWarned100(ctx context.Context, month pgtype.Date) (int64, error) {
	result, err := q.db.Exec(ctx, markRelayUsageWarned100, month)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markRelayUsageWarned80 = `-- name: MarkRelayUsageWarned80 :execrows
UPDATE relay_session_usage
SET warned_80_at = now(), updated_at = now()
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND month = $1
  AND warned_80_at IS NULL
`

// Claims the right to send the single 80% warning email for this month
// (0 rows = another request already sent it).
func (q *Queries) MarkRelayUsageWarned80(ctx context.Context, month pgtype.Date) (int64, error) {
	result, err := q.db.Exec(ctx, markRelayUsageWarned80, month)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
