// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings_revisions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSettingsRevision = `-- name: GetSettingsRevision :one
SELECT snapshot
FROM settings_revisions
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND project_id = $1
  AND resource_kind = $2
  AND resource_id = $3
  AND revision = $4
`

type GetSettingsRevisionParams struct {
	ProjectID    int64
	ResourceKind string
	ResourceID   int64
	Revision     int64
}

func (q *Queries) GetSettingsRevision(ctx context.Context, arg GetSettingsRevisionParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSettingsRevision,
		arg.ProjectID,
		arg.ResourceKind,
		arg.ResourceID,
		arg.Revision,
	)
	var snapshot []byte
	err := row.Scan(&snapshot)
	return snapshot, err
}

const insertSettingsRevision = `-- name: InsertSettingsRevision :exec
INSERT INTO settings_revisions (
    tenant_id, project_id, resource_kind, resource_id, revision, snapshot,
    actor_user_id, mcp_token_id, source
)
VALUES (
    current_setting('app.tenant_id', true)::bigint,
    $1, $2, $3,
    $4, $5, $6,
    $7, $8
)
`

type InsertSettingsRevisionParams struct {
	ProjectID    int64
	ResourceKind string
	ResourceID   int64
	Revision     int64
	Snapshot     []byte
	ActorUserID  *int64
	McpTokenID   *int64
	Source       string
}

func (q *Queries) InsertSettingsRevision(ctx context.Context, arg InsertSettingsRevisionParams) error {
	_, err := q.db.Exec(ctx, insertSettingsRevision,
		arg.ProjectID,
		arg.ResourceKind,
		arg.ResourceID,
		arg.Revision,
		arg.Snapshot,
		arg.ActorUserID,
		arg.McpTokenID,
		arg.Source,
	)
	return err
}

const latestSettingsRevision = `-- name: LatestSettingsRevision :one
SELECT COALESCE(MAX(revision), 0)::bigint
FROM settings_revisions
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND project_id = $1
  AND resource_kind = $2
  AND resource_id = $3
`

type LatestSettingsRevisionParams struct {
	ProjectID    int64
	ResourceKind string
	ResourceID   int64
}

func (q *Queries) LatestSettingsRevision(ctx context.Context, arg LatestSettingsRevisionParams) (int64, error) {
	row := q.db.QueryRow(ctx, latestSettingsRevision, arg.ProjectID, arg.ResourceKind, arg.ResourceID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listSettingsRevisions = `-- name: ListSettingsRevisions :many
SELECT revision, snapshot, actor_user_id, mcp_token_id, source, created_at
FROM settings_revisions
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND project_id = $1
  AND resource_kind = $2
  AND resource_id = $3
ORDER BY revision DESC
`

type ListSettingsRevisionsParams struct {
	ProjectID    int64
	ResourceKind string
	ResourceID   int64
}

type ListSettingsRevisionsRow struct {
	Revision    int64
	Snapshot    []byte
	ActorUserID *int64
	McpTokenID  *int64
	Source      string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListSettingsRevisions(ctx context.Context, arg ListSettingsRevisionsParams) ([]ListSettingsRevisionsRow, error) {
	rows, err := q.db.Query(ctx, listSettingsRevisions, arg.ProjectID, arg.ResourceKind, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSettingsRevisionsRow
	for rows.Next() {
		var i ListSettingsRevisionsRow
		if err := rows.Scan(
			&i.Revision,
			&i.Snapshot,
			&i.ActorUserID,
			&i.McpTokenID,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneSettingsRevisions = `-- name: PruneSettingsRevisions :exec
DELETE FROM settings_revisions
WHERE tenant_id = current_setting('app.tenant_id', true)::bigint
  AND project_id = $1
  AND resource_kind = $2
  AND resource_id = $3
  AND revision <= $4
`

type PruneSettingsRevisionsParams struct {
	ProjectID    int64
	ResourceKind string
	ResourceID   int64
	BelowOrAt    int64
}

func (q *Queries) PruneSettingsRevisions(ctx context.Context, arg PruneSettingsRevisionsParams) error {
	_, err := q.db.Exec(ctx, pruneSettingsRevisions,
		arg.ProjectID,
		arg.ResourceKind,
		arg.ResourceID,
		arg.BelowOrAt,
	)
	return err
}
