// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sso_connections.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countControlPanelUserConnections = `-- name: CountControlPanelUserConnections :one
SELECT count(*)::bigint
FROM control_panel_user_connections
WHERE control_panel_user_id = $1
`

func (q *Queries) CountControlPanelUserConnections(ctx context.Context, controlPanelUserID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countControlPanelUserConnections, controlPanelUserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countPlayerAccountConnections = `-- name: CountPlayerAccountConnections :one
SELECT count(*)::bigint
FROM player_account_connections
WHERE player_account_id = $1
`

func (q *Queries) CountPlayerAccountConnections(ctx context.Context, playerAccountID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPlayerAccountConnections, playerAccountID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteControlPanelUserConnection = `-- name: DeleteControlPanelUserConnection :execrows
DELETE FROM control_panel_user_connections
WHERE control_panel_user_id = $1
  AND provider = $2
`

type DeleteControlPanelUserConnectionParams struct {
	ControlPanelUserID int64
	Provider           string
}

func (q *Queries) DeleteControlPanelUserConnection(ctx context.Context, arg DeleteControlPanelUserConnectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteControlPanelUserConnection, arg.ControlPanelUserID, arg.Provider)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePlayerAccountConnection = `-- name: DeletePlayerAccountConnection :execrows
DELETE FROM player_account_connections
WHERE player_account_id = $1
  AND provider = $2
`

type DeletePlayerAccountConnectionParams struct {
	PlayerAccountID pgtype.UUID
	Provider        string
}

func (q *Queries) DeletePlayerAccountConnection(ctx context.Context, arg DeletePlayerAccountConnectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePlayerAccountConnection, arg.PlayerAccountID, arg.Provider)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getControlPanelUserByConnection = `-- name: GetControlPanelUserByConnection :one
SELECT
    u.id,
    u.email::text AS email,
    u.is_platform_admin,
    u.email_verified_at,
    u.disabled_at
FROM control_panel_user_connections c
JOIN control_panel_users u ON u.id = c.control_panel_user_id
WHERE c.provider = $1
  AND c.subject = $2
`

type GetControlPanelUserByConnectionParams struct {
	Provider string
	Subject  string
}

type GetControlPanelUserByConnectionRow struct {
	ID              int64
	Email           string
	IsPlatformAdmin bool
	EmailVerifiedAt pgtype.Timestamptz
	DisabledAt      pgtype.Timestamptz
}

// Status-blind like GetControlPanelUserAnyStatusByEmail: the caller refuses a
// disabled user with the same answer as an unknown connection.
func (q *Queries) GetControlPanelUserByConnection(ctx context.Context, arg GetControlPanelUserByConnectionParams) (GetControlPanelUserByConnectionRow, error) {
	row := q.db.QueryRow(ctx, getControlPanelUserByConnection, arg.Provider, arg.Subject)
	var i GetControlPanelUserByConnectionRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.IsPlatformAdmin,
		&i.EmailVerifiedAt,
		&i.DisabledAt,
	)
	return i, err
}

const getPlayerAccountByConnection = `-- name: GetPlayerAccountByConnection :one

SELECT
    a.id,
    a.email::text AS email,
    a.display_name,
    a.disabled_at,
    a.session_epoch
FROM player_account_connections c
JOIN player_accounts a ON a.id = c.player_account_id
WHERE c.provider = $1
  AND c.subject = $2
`

type GetPlayerAccountByConnectionParams struct {
	Provider string
	Subject  string
}

type GetPlayerAccountByConnectionRow struct {
	ID           pgtype.UUID
	Email        string
	DisplayName  *string
	DisabledAt   pgtype.Timestamptz
	SessionEpoch int32
}

// Single sign-on connections. Both tables are platform-global (no tenant
// RLS): every query here runs through db.Pool.BootstrapQ. The subject always
// comes from a verified provider round trip, never from client input.
func (q *Queries) GetPlayerAccountByConnection(ctx context.Context, arg GetPlayerAccountByConnectionParams) (GetPlayerAccountByConnectionRow, error) {
	row := q.db.QueryRow(ctx, getPlayerAccountByConnection, arg.Provider, arg.Subject)
	var i GetPlayerAccountByConnectionRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.DisabledAt,
		&i.SessionEpoch,
	)
	return i, err
}

const insertControlPanelUserConnection = `-- name: InsertControlPanelUserConnection :exec
INSERT INTO control_panel_user_connections (control_panel_user_id, provider, subject)
VALUES ($1, $2, $3)
`

type InsertControlPanelUserConnectionParams struct {
	ControlPanelUserID int64
	Provider           string
	Subject            string
}

func (q *Queries) InsertControlPanelUserConnection(ctx context.Context, arg InsertControlPanelUserConnectionParams) error {
	_, err := q.db.Exec(ctx, insertControlPanelUserConnection, arg.ControlPanelUserID, arg.Provider, arg.Subject)
	return err
}

const insertPlayerAccountConnection = `-- name: InsertPlayerAccountConnection :exec
INSERT INTO player_account_connections (player_account_id, provider, subject)
VALUES ($1, $2, $3)
`

type InsertPlayerAccountConnectionParams struct {
	PlayerAccountID pgtype.UUID
	Provider        string
	Subject         string
}

func (q *Queries) InsertPlayerAccountConnection(ctx context.Context, arg InsertPlayerAccountConnectionParams) error {
	_, err := q.db.Exec(ctx, insertPlayerAccountConnection, arg.PlayerAccountID, arg.Provider, arg.Subject)
	return err
}

const listControlPanelUserConnections = `-- name: ListControlPanelUserConnections :many
SELECT provider, created_at
FROM control_panel_user_connections
WHERE control_panel_user_id = $1
ORDER BY provider
`

type ListControlPanelUserConnectionsRow struct {
	Provider  string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListControlPanelUserConnections(ctx context.Context, controlPanelUserID int64) ([]ListControlPanelUserConnectionsRow, error) {
	rows, err := q.db.Query(ctx, listControlPanelUserConnections, controlPanelUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListControlPanelUserConnectionsRow
	for rows.Next() {
		var i ListControlPanelUserConnectionsRow
		if err := rows.Scan(&i.Provider, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerAccountConnections = `-- name: ListPlayerAccountConnections :many
SELECT provider, created_at
FROM player_account_connections
WHERE player_account_id = $1
ORDER BY provider
`

type ListPlayerAccountConnectionsRow struct {
	Provider  string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListPlayerAccountConnections(ctx context.Context, playerAccountID pgtype.UUID) ([]ListPlayerAccountConnectionsRow, error) {
	rows, err := q.db.Query(ctx, listPlayerAccountConnections, playerAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayerAccountConnectionsRow
	for rows.Next() {
		var i ListPlayerAccountConnectionsRow
		if err := rows.Scan(&i.Provider, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockControlPanelUserSignInMethods = `-- name: LockControlPanelUserSignInMethods :one
SELECT (password_hash IS NOT NULL)::boolean AS has_password
FROM control_panel_users
WHERE id = $1
FOR UPDATE
`

// Same row lock as LockPlayerAccountSignInMethods.
func (q *Queries) LockControlPanelUserSignInMethods(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, lockControlPanelUserSignInMethods, id)
	var has_password bool
	err := row.Scan(&has_password)
	return has_password, err
}

const lockPlayerAccountSignInMethods = `-- name: LockPlayerAccountSignInMethods :one
SELECT (password_hash IS NOT NULL)::boolean AS has_password
FROM player_accounts
WHERE id = $1
FOR UPDATE
`

// Row lock for the last-sign-in-method rule: two concurrent unlink requests
// serialize here, so they cannot both pass the count and remove the last
// two methods.
func (q *Queries) LockPlayerAccountSignInMethods(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, lockPlayerAccountSignInMethods, id)
	var has_password bool
	err := row.Scan(&has_password)
	return has_password, err
}

const touchControlPanelUserConnection = `-- name: TouchControlPanelUserConnection :exec
UPDATE control_panel_user_connections
SET last_used_at = now()
WHERE provider = $1
  AND subject = $2
`

type TouchControlPanelUserConnectionParams struct {
	Provider string
	Subject  string
}

func (q *Queries) TouchControlPanelUserConnection(ctx context.Context, arg TouchControlPanelUserConnectionParams) error {
	_, err := q.db.Exec(ctx, touchControlPanelUserConnection, arg.Provider, arg.Subject)
	return err
}

const touchPlayerAccountConnection = `-- name: TouchPlayerAccountConnection :exec
UPDATE player_account_connections
SET last_used_at = now()
WHERE provider = $1
  AND subject = $2
`

type TouchPlayerAccountConnectionParams struct {
	Provider string
	Subject  string
}

func (q *Queries) TouchPlayerAccountConnection(ctx context.Context, arg TouchPlayerAccountConnectionParams) error {
	_, err := q.db.Exec(ctx, touchPlayerAccountConnection, arg.Provider, arg.Subject)
	return err
}
